### ISSUE TITLE
Code coverage fails on io/*-lexer.l not found

### ISSUE THREAD

**Issue by GroteGnoom** [igraph/igraph#1614] opened 2021-01-19 16:52 UTC
**Describe the bug**
When generating code coverage, I get a 

> genhtml: ERROR: cannot read /home/daniel/Documents/repos/igraph/io/lgl-lexer.l

I used a clean build directory, and the type of lexer switches. Sometimes it's ncol, sometimes dl, sometimes pajek.
The file
> ./coverage/io/lgl-lexer.l.gcov.html

does exist.

**To reproduce**
Follow the steps in
https://github.com/igraph/igraph/wiki/Generating-test-coverage-reports

**Version information**
The current develop version at 665d22206cfe46e03adb82c4a2096ab37f358bde
cmake 3.16.3
GNU Make 4.2.1
flex 2.6.4
bison (GNU Bison) 3.5.1
gcov (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
lcov: LCOV version 1.14

**other info**
I do get these warnings, which seem harmless, but are for the related parsers:

> [ 13%] [FLEX][pajek_lexer] Building scanner with flex 2.6.4
> [ 13%] [BISON][dl_parser] Building parser with bison 3.5.1
> /home/daniel/Documents/repos/igraph/src/io/dl-parser.y:78.1-12: warning: deprecated directive: ‘%pure-parser’, use ‘%define api.pure’ [-Wdeprecated]
>    78 | %pure-parser
>       | ^~~~~~~~~~~~
>       | %define api.pure
> /home/daniel/Documents/repos/igraph/src/io/dl-parser.y:81.1-27: warning: deprecated directive: ‘%name-prefix="igraph_dl_yy"’, use ‘%define api.prefix {igraph_dl_yy}’ [-Wdeprecated]
>    81 | %name-prefix="igraph_dl_yy"
>       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
>       | %define api.prefix {igraph_dl_yy}
> /home/daniel/Documents/repos/igraph/src/io/dl-parser.y:84.1-14: warning: deprecated directive: ‘%error-verbose’, use ‘%define parse.error verbose’ [-Wdeprecated]
>    84 | %error-verbose
>       | ^~~~~~~~~~~~~~
>       | %define parse.error verbose
> /home/daniel/Documents/repos/igraph/src/io/dl-parser.y: warning: 20 shift/reduce conflicts [-Wconflicts-sr]
> /home/daniel/Documents/repos/igraph/src/io/dl-parser.y: warning: 3 reduce/reduce conflicts [-Wconflicts-rr]
> /home/daniel/Documents/repos/igraph/src/io/dl-parser.y: warning: fix-its can be applied.  Rerun with option '--update'. [-Wother]
> [ 18%] [FLEX][dl_lexer] Building scanner with flex 2.6.4
> [ 18%] [BISON][gml_parser] Building parser with bison 3.5.1
> /home/daniel/Documents/repos/igraph/src/io/gml-parser.y:85.1-12: warning: deprecated directive: ‘%pure-parser’, use ‘%define api.pure’ [-Wdeprecated]
>    85 | %pure-parser
>       | ^~~~~~~~~~~~
>       | %define api.pure
> /home/daniel/Documents/repos/igraph/src/io/gml-parser.y:88.1-28: warning: deprecated directive: ‘%name-prefix="igraph_gml_yy"’, use ‘%define api.prefix {igraph_gml_yy}’ [-Wdeprecated]
>    88 | %name-prefix="igraph_gml_yy"
>       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
>       | %define api.prefix {igraph_gml_yy}
> /home/daniel/Documents/repos/igraph/src/io/gml-parser.y:91.1-14: warning: deprecated directive: ‘%error-verbose’, use ‘%define parse.error verbose’ [-Wdeprecated]
>    91 | %error-verbose
>       | ^~~~~~~~~~~~~~
>       | %define parse.error verbose
> /home/daniel/Documents/repos/igraph/src/io/gml-parser.y: warning: fix-its can be applied.  Rerun with option '--update'. [-Wother]
> [ 18%] [FLEX][gml_lexer] Building scanner with flex 2.6.4
> [ 18%] [BISON][lgl_parser] Building parser with bison 3.5.1
> /home/daniel/Documents/repos/igraph/src/io/lgl-parser.y:73.1-12: warning: deprecated directive: ‘%pure-parser’, use ‘%define api.pure’ [-Wdeprecated]
>    73 | %pure-parser
>       | ^~~~~~~~~~~~
>       | %define api.pure
> /home/daniel/Documents/repos/igraph/src/io/lgl-parser.y:76.1-28: warning: deprecated directive: ‘%name-prefix="igraph_lgl_yy"’, use ‘%define api.prefix {igraph_lgl_yy}’ [-Wdeprecated]
>    76 | %name-prefix="igraph_lgl_yy"
>       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
>       | %define api.prefix {igraph_lgl_yy}
> /home/daniel/Documents/repos/igraph/src/io/lgl-parser.y:79.1-14: warning: deprecated directive: ‘%error-verbose’, use ‘%define parse.error verbose’ [-Wdeprecated]
>    79 | %error-verbose
>       | ^~~~~~~~~~~~~~
>       | %define parse.error verbose
> /home/daniel/Documents/repos/igraph/src/io/lgl-parser.y: warning: fix-its can be applied.  Rerun with option '--update'. [-Wother]
> [ 18%] [FLEX][lgl_lexer] Building scanner with flex 2.6.4
> [ 18%] [BISON][ncol_parser] Building parser with bison 3.5.1
> /home/daniel/Documents/repos/igraph/src/io/ncol-parser.y:74.1-12: warning: deprecated directive: ‘%pure-parser’, use ‘%define api.pure’ [-Wdeprecated]
>    74 | %pure-parser
>       | ^~~~~~~~~~~~
>       | %define api.pure
> /home/daniel/Documents/repos/igraph/src/io/ncol-parser.y:77.1-29: warning: deprecated directive: ‘%name-prefix="igraph_ncol_yy"’, use ‘%define api.prefix {igraph_ncol_yy}’ [-Wdeprecated]
>    77 | %name-prefix="igraph_ncol_yy"
>       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>       | %define api.prefix {igraph_ncol_yy}
> /home/daniel/Documents/repos/igraph/src/io/ncol-parser.y:80.1-14: warning: deprecated directive: ‘%error-verbose’, use ‘%define parse.error verbose’ [-Wdeprecated]
>    80 | %error-verbose
>       | ^~~~~~~~~~~~~~
>       | %define parse.error verbose
> /home/daniel/Documents/repos/igraph/src/io/ncol-parser.y: warning: fix-its can be applied.  Rerun with option '--update'. [-Wother]
> [ 18%] [FLEX][ncol_lexer] Building scanner with flex 2.6.4
> [ 18%] [BISON][pajek_parser] Building parser with bison 3.5.1
> /home/daniel/Documents/repos/igraph/src/io/pajek-parser.y:110.1-12: warning: deprecated directive: ‘%pure-parser’, use ‘%define api.pure’ [-Wdeprecated]
>   110 | %pure-parser
>       | ^~~~~~~~~~~~
>       | %define api.pure
> /home/daniel/Documents/repos/igraph/src/io/pajek-parser.y:113.1-30: warning: deprecated directive: ‘%name-prefix="igraph_pajek_yy"’, use ‘%define api.prefix {igraph_pajek_yy}’ [-Wdeprecated]
>   113 | %name-prefix="igraph_pajek_yy"
>       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>       | %define api.prefix {igraph_pajek_yy}
> /home/daniel/Documents/repos/igraph/src/io/pajek-parser.y:116.1-14: warning: deprecated directive: ‘%error-verbose’, use ‘%define parse.error verbose’ [-Wdeprecated]
>   116 | %error-verbose
>       | ^~~~~~~~~~~~~~
>       | %define parse.error verbose
> /home/daniel/Documents/repos/igraph/src/io/pajek-parser.y: warning: 6 shift/reduce conflicts [-Wconflicts-sr]
> /home/daniel/Documents/repos/igraph/src/io/pajek-parser.y: warning: fix-its can be applied.  Rerun with option '--update'. [-Wother]
> Scanning dependencies of target igraph

I tried the suggested `--update`s, but that messed things up even more.

**Comment by ntamas** [comment] 2021-01-21 13:13
Can you please try this?

```
mkdir build
cd build
cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DIGRAPH_ENABLE_CODE_COVERAGE=ON
make
VERBOSE=1 make coverage
```

The important part is the output of `VERBOSE=1 make coverage` -- I would like to know what arguments are passed to `genhtml` when the coverage report is about to be generated.

**Comment by GroteGnoom** [comment] 2021-01-21 13:30
I think these are the calls:
```
/usr/bin/lcov --gcov-tool /usr/bin/gcov --directory . -b /home/daniel/Documents/repos/igraph --capture --output-file coverage.capture
```
```
/usr/bin/lcov --gcov-tool /usr/bin/gcov -a coverage.base -a coverage.capture --output-file coverage.total
```
```
/usr/bin/genhtml --demangle-cpp -o coverage coverage.info
Reading data file coverage.info
Found 350 entries.
Found common filename prefix "/home/daniel/Documents/repos/igraph"
Writing .css and .png files.
Generating output.
Processing file build/src/io/parsers/gml-parser.c
Processing file build/src/io/parsers/ncol-lexer.c
Processing file build/src/io/parsers/lgl-parser.c
Processing file build/src/io/parsers/lgl-lexer.c
Processing file build/src/io/parsers/gml-lexer.c
Processing file build/src/io/parsers/dl-parser.c
Processing file build/src/io/parsers/pajek-lexer.c
Processing file build/src/io/parsers/ncol-parser.c
Processing file build/src/io/parsers/pajek-parser.c
Processing file build/src/io/parsers/dl-lexer.c
Processing file io/lgl-lexer.l
genhtml: ERROR: cannot read /home/daniel/Documents/repos/igraph/io/lgl-lexer.l
```
Is that the info you wanted?

**Comment by ntamas** [comment] 2021-01-21 13:40
Yes, thanks. For comparison, the output on my machine looks like this:

```
/usr/local/bin/genhtml --demangle-cpp -o coverage coverage.info
Reading data file coverage.info
Found 301 entries.
Found common filename prefix "/Users/tamas/dev/igraph/igraph"
Writing .css and .png files.
Generating output.
Processing file src/version.c
Processing file src/centrality/prpack.cpp
Processing file src/centrality/betweenness.c
Processing file src/centrality/centralization.c
Processing file src/centrality/coreness.c
Processing file src/centrality/closeness.c
...and so on...
```

Clearly, the paths in `coverage.info` are probably wrong in your case, there is no file named `io/lgl-lexer.l` in the source distribution, only `src/io/lgl-lexer.l`.

Actually, I also had problems with these files on my machine, that's exactly why we are setting up the coverage analysis like this in `CMakeLists.txt`:

```
setup_target_for_coverage_lcov(
    NAME coverage
    EXECUTABLE "${CMAKE_COMMAND}" "--build" "${CMAKE_BINARY_DIR}" "--target" "check"
    # Generated files are excluded; apparently the CodeCoverage script has some
    # problems with them. Yes, the exclusion is correct, it refers to a nonexistent
    # directory that somehow gets into the coverage resolts. /Applications is for
    # macOS -- it excludes files from the macOS SDK.
    EXCLUDE "io/parsers/*" "/Applications/Xcode*" "examples/*" "tests/*"
)
```

I cannot reproduce your issue on my machine so I'd like to ask you to experiment a little bit with the above line in `CMakeLists.txt`. For me it seems like the `EXCLUDE` directive does not take effect. This could be caused by:

1. CMake's parser gets confused with the comments I dropped in the middle of the invocation of `setup_target_for_coverage_lcon()` -- try removing the comment and see whether it works

2. `/Applications/Xcode*` is nonexistent on Linux, but maybe it somehow confuses the exclusion logic. Try dropping `/Applications/Xcode*` from the excludes directive and see whether it works

3. If these two attempts don't solve the problem, look up the `setup_target_for_coverage_lcov` function in `etc/cmake/CodeCoverage.cmake` and try putting `message(STATUS ${EXCLUDE})` in the main `foreach` loop of the function to see what exactly CMake tries to exclude.

**Comment by GroteGnoom** [comment] 2021-01-21 13:46
Allright, I'll try that!

**Comment by ntamas** [comment] 2021-01-25 14:59
Okay, I've added `io/*.l` to the coverage excludes now. Please confirm that it solves the problem on your end and then I'll close this issue.

**Comment by GroteGnoom** [comment] 2021-01-25 16:28
make coverage now fails on
```
163/300 Test #163: graphml....................................***Failed    0.29 sec                                                                                                                                                                                             
Error at src/io/graphml.c:1665 : Write failed - File operation error.                                                                                                                                                                                                           
Test exited abnormally with error: Child aborted                                                                                                                                                                                                                                
=========================================                                                                                                                                                                                                                                       
CMake Error at /home/daniel/Documents/repos/igraph/etc/cmake/run_legacy_test.cmake:45 (message):                                                                                                                                                                                
  Exiting test.                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                       
243/300 Test #243: cattributes2...............................***Failed    0.30 sec                                                                                                                                                                                           
Error at src/io/graphml.c:1729 : Write failed - File operation error.                                                                                                                                                                                                         
Test exited abnormally with error: Child aborted                                                                                                                                                                                                                              
=========================================                                                                                                                                                                                                                                     
CMake Error at /home/daniel/Documents/repos/igraph/etc/cmake/run_legacy_test.cmake:45 (message):                                                                                                                                                                              
    Exiting test.                                                                                                                                                                                                                                                               
```
so I'm not sure.

[..]/igraph/examples/simple/test2.gxl is created, which seems strange.

**Closed** 2021-01-25 16:41 UTC
