### ISSUE TITLE
community_leading_eigenvector() fails on some graphs with "Starting vector is zero"

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2232] opened 2022-10-09 08:37 UTC
**Describe the bug**

`igraph_community_leading_eigenvector()` fails on some graphs with 

> At core/community/leading_eigenvector.c:752 : ARPACK call failed, Starting vector is zero

This was revealed by the R test suite. The problem exists on the `release/0.9` branch. In Mathematica there is also a crash. Still investigating.

**To reproduce**

Zero-based edge list, 20 vertices:

```
5	6
3	7
0	8
3	8
4	9
2	11
2	12
4	13
10	14
2	15
3	15
10	16
2	17
16	17
4	19
```

**Version information**

Only tested `release/0.9`

**Comment by ntamas** [comment] 2022-10-09 09:15
Also fails in Python; it’s on my radar but I haven’t had time to dig into this. Most likely it is caused by the change to random start vectors generated on the igraph side instead of LAPACK. First thing tomorrow unless I find time for it earlier.

**Comment by szhorvat** [comment] 2022-10-09 11:14
Why is the eigenvalue problem still solved twice, is it necessary?

https://github.com/igraph/igraph/blob/master/src/community/leading_eigenvector.c#L725

It is during the second solution that this error occurs. And indeed the starting vector is all-zero here. However, it isn't initialized to begin with, which doesn't seem right.

**Comment by szhorvat** [comment] 2022-10-09 11:15
Can you expand this cryptic comment please?

https://github.com/igraph/igraph/blob/master/include/igraph_arpack.h#L288

**Comment by szhorvat** [comment] 2022-10-09 13:43
Fixed the crash-on-error that affected the Mma interface. This won't affect R/igraph.

**Comment by ntamas** [comment] 2022-10-09 22:14
> Can you expand this cryptic comment please?

A few lines above the line you indicated we have this:

```
* \member di Memory for eigenvalues, non-symmetric case only.
 * \member workev Working memory, non-symmetric case only.
```

I don't think I can tell any more than this; these are working memory areas for ARPACK that are needed in the non-symmetric case, but I haven't followed up the ARPACK code to understand what exactly they are for.

**Comment by szhorvat** [comment] 2022-10-10 09:14
After the last commit, about 50 graphs still fail occasionally from the graph atlas (1253 graphs).

The worst offender is:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/1212871/194833626-059fd028-05fd-41f6-9487-a124668c11c1.png">

1-based edge list (Mma format):

```
{{3, 6}, {4, 6}, {5, 6}, {4, 5}, {2, 6}, {1, 6}}
```

0-based (C format):

```
{2, 5, 3, 5, 4, 5, 3, 4, 1, 5, 0, 5}
```

**Comment by szhorvat** [comment] 2022-10-10 09:29
I also tried with ARPACK-NG 3.8.0. While the situation is a bit better, there are still many failures. Interestingly, with certain graphs, it _always_ fails with "Starting vector is zero". One such graph is:

```
{{4, 7}, {1, 7}, {3, 7}, {6, 7}, {2, 7}, {5, 7}}

{3, 6, 0, 6, 2, 6, 5, 6, 1, 6, 4, 6}
```

<img width="360" alt="image" src="https://user-images.githubusercontent.com/1212871/194836093-f02069ce-df70-4a8a-99e6-1439a78acb7f.png">

Note that the vertex ordering is important here.

With the bundled ARPACK, there was no graph in the atlas for which is failed 100% of the time.

**Comment by szhorvat** [comment] 2022-10-10 09:45
The above commit reduces the overall failure rate by a factor of several (maybe 7-8) with both the vendored ARPACK and ARPACK-NG, but it's still not perfect.

**Comment by szhorvat** [comment] 2022-10-10 10:03
R test suite passes now, but again: it's still not difficult to bring out problems by stress testing.

**Comment by szhorvat** [comment] 2022-10-10 10:38
Regarding the failing `levc-stress` test: 

Perhaps, when there was no convergence, we should try several times, as hacky as that is?

**Comment by ntamas** [comment] 2022-10-10 22:06
> The above commit reduces the overall failure rate by a factor of several (maybe 7-8) with both the vendored ARPACK and ARPACK-NG, but it's still not perfect.

That commit somehow resulted in deterministic failures for me on my machine with the stress test. I kept your changes but increased the iteration count to 10000, and this seems to be satisfactory both for my local tests and for the CI.

I'll add a random seed.

**Comment by ntamas** [comment] 2022-10-10 22:09
> Perhaps, when there was no convergence, we should try several times, as hacky as that is?

I don't really like that tbh.

**Comment by ntamas** [comment] 2022-10-10 22:33
I think we can close this now; all tests seem to pass everywhere. (The current failures for the Python interface are unrelated; I'm finding it increasingly harder to set up the list of test dependencies in a way that there are pre-compiled wheels for all the stuff we need for tests, across Python 3.7 to Python 3.11; I'm working on that).

**Closed** 2022-10-10 22:34 UTC
