### ISSUE TITLE
Undefined reference to 'igraph_sparsemat'

### ISSUE THREAD

**Issue by advaitb** [igraph/igraph#1242] opened 2019-08-20 19:08 UTC
Hi,

1) I've installed the igraph c library successfully, however while running the sparsemat functions I run into ld error caused by undefined reference. I don't seem to have this problem when accessing other functions like vector_t or matrix_t. I had a look at Issue #988 and made the respective changes but I'm not sure how to resolve this.Any idea how I can use sparsemat? 

`/tmp/ccklFFmC.o: In function `main':
test.cpp:(.text+0xce): undefined reference to `igraph_sparsemat_init(igraph_sparsemat_t*, int, int, int)'
test.cpp:(.text+0x174): undefined reference to `igraph_sparsemat_entry(igraph_sparsemat_t*, int, int, double)'
test.cpp:(.text+0x1ec): undefined 
reference to `igraph_sparsemat(igraph_s*, igraph_sparsemat_t const*, int)'
test.cpp:(.text+0x24b): undefined reference to `igraph_sparsemat_destroy(igraph_sparsemat_t*)'
collect2: error: ld returned 1 exit status`

2) Also, is there anyway to convert spmatrix into a graph?

Thanks!

Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] This issue is for the C core of igraph.
- [ ] This issue is a bug report or a feature request, not a support question.

**Comment by vtraag** [comment] 2019-08-20 19:46
Could you share some minimal reproducible code that shows the exact mentioned problem? What version of `igraph` did you install? 

To answer your second question, yes you can use [`igraph_sparsemat`](https://igraph.org/c/doc/ch07.html#igraph_sparsemat).

**Comment by advaitb** [comment] 2019-08-20 20:21
Hi @vtraag , thanks for your prompt response. I'm using v0.7.1. Here is the code I'm trying to run:
```
#include <igraph.h>
#include <cstdlib>
#include <vector>
#include <iostream>
#include <ctime>
#include <string>
#include <igraph_sparsemat.h>


#define SIZE 900000
using namespace std;


void printConsole(string printThis){
    time_t result = time(nullptr);
    cout<<asctime(localtime(&result))<<" "<<printThis<<endl;
}


int main(){

        igraph_t graph;
        igraph_sparsemat_t mat;
        igraph_vector_t cores;
        igraph_sparsemat_init(&mat, SIZE, SIZE, 805000000000);
        long i;
        printConsole("Start populating adjmat");
        for (i=0;i<SIZE-700000;i++){
                igraph_sparsemat_entry(&mat,i,i+1,1);
        }
        printConsole("Built adjmat");
        igraph_sparsemat(&graph,&mat,0);
        printConsole("Built graph");
        igraph_sparsemat_destroy(&mat);
        printConsole("Start Kcore");
        igraph_vector_init(&cores,SIZE);
        igraph_coreness(&graph,&cores, IGRAPH_ALL);
        printConsole("Finished Kcore");
        igraph_vector_destroy(&cores);
        igraph_destroy(&graph);
        return 0;
```
Thanks!

**Comment by vtraag** [comment] 2019-08-20 21:19
You are compiling using `C++`. You should enclose the inclusion in an `extern "C"` because `igraph` is a `C` library. You only need to include `igraph.h`, since it already includes `igraph_sparsemat.h`.

The following code compiles correctly, also when interpreted as C++.

```
extern "C"
{
  #include <igraph.h>
}

int main(){

        igraph_sparsemat_t mat;
        igraph_sparsemat_init(&mat, 4, 4, 3);
        return 0;
}
```

Please note that 805000000000 will be interpreted as an integer, which will overflow.

I believe you are right, there does not seem to be a function for creating a `igraph_t` from a `igraph_spmatrix_t`.

**Comment by advaitb** [comment] 2019-08-20 21:41
@vtraag Thanks that solved it, just another query if I may, how accurate should the nzmax parameter in sparsemat_init need to be, can I just set it to max int for really large graphs?

**Comment by vtraag** [comment] 2019-08-21 04:52
`nzmax` can be anything you like. It pre-allocates the requested number of elements, but if you set new elements new memory is dynamically  allocated if necessary. Just any rough estimate will do. Note that max int requires about 8GB of memory, you probably don't want to do that.

**Closed** 2019-08-21 04:52 UTC
