### ISSUE TITLE
The macro STR() doesn't have the  prefix IGRAPH_

### ISSUE THREAD

**Issue by yurivict** [igraph/igraph#1460] opened 2020-08-15 19:24 UTC
This is the place in the installed headers: https://github.com/igraph/igraph/blob/master/include/igraph_strvector.h#L55

Please change the ```STR()``` macro to ```IGRAPH_STR()```.

**Comment by szhorvat** [comment] 2020-08-15 20:21
Duplicate of #1001. Please post in that issue and explain why you want to change this. If it conflicts with another library, show which one.

**Closed by szhorvat** 2020-08-15 20:21 UTC

**Comment by yurivict** [comment] 2020-08-15 20:49
It's common sense that global namespace should be clean. I routinely use the macro ```STR``` in my C++ code because it's convenient. It is amazing that there's even a debate about this.

**Comment by iosonofabio** [comment] 2020-08-15 21:30
Thanks @yurivict . Yes it's amazing, right? But unfortunately it takes time to make the change, document, break API, deprecate, and finally abandon. I'd be happy if you want to follow through with those, please start with a PR and we'll guide you.

We all love clean namespaces - but hate undocumented API breaks too 😉

**Comment by szhorvat** [comment] 2020-08-16 05:56
Please let us continue the discussion in #1001 as that is where it has started. We have not yet made a collective decision to make this change, and there are also arguments against doing it. Therefore I would not solicit a PR at this point (as that effectively commits to making this breaking change). Should the decision be made, renaming is fairly easy with a smart IDE.
