### ISSUE TITLE
Build fails on CentOS/

### ISSUE THREAD

**Issue by chrchr** [igraph/igraph#1021] opened 2017-07-28 22:35 UTC
Hi! igraph build fails on this CentOS computer.

```
> install.packages("igraph")
. . . 
ng --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c foreign-graphml.c -o foreign-graphml.o
foreign-graphml.c: In function ‘igraph_write_graph_graphml’:
foreign-graphml.c:1408:46: error: expected ‘)’ before ‘GRAPHML_NAMESPACE_URI’
   ret=fprintf(outstream, "<graphml xmlns=\"" GRAPHML_NAMESPACE_URI "\"\n");
                                              ^
foreign-graphml.c:1412:59: error: expected ‘)’ before ‘GRAPHML_NAMESPACE_URI’
   ret=fprintf(outstream, "         xsi:schemaLocation=\"" GRAPHML_NAMESPACE_URI
                                                           ^
foreign-graphml.c:1414:38: error: expected ‘)’ before ‘GRAPHML_NAMESPACE_URI’
   ret=fprintf(outstream, "         " GRAPHML_NAMESPACE_URI "/1.0/graphml.xsd\">
                                      ^
```

c++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)

CentOS Linux release 7.3.1611 (Core) 

R version: 
```
R version 3.4.0 (2017-04-21) -- "You Stupid Darkness"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)
```

Thank you!

**Comment by gaborcsardi** [comment] 2017-07-29 06:41
Duplicate of #1019 1019

**Closed by gaborcsardi** 2017-07-29 06:41 UTC
