### ISSUE TITLE
[feature request] Add arrow with T-shaped head

### ISSUE THREAD

**Issue by zjf19870628** [igraph/igraph#832] opened 2015-06-13 02:58 UTC
In bioinformatics, arrow with T-shaped head is often used to represent gene regulation. Advise to add this feature.

**Comment by ntamas** [comment] 2015-06-13 23:39
Is this for the R or the Python interface of igraph? (The C core does not provide any plotting functionality).

**Comment by zjf19870628** [comment] 2015-06-14 02:37
I am using R package "igraph". In R package "shape", I can use function
Arrows() to plot arrows with various arrowheads, including T-shaped head.
But "igraph" only provides one type “>”.

**Comment by ntamas** [comment] 2015-06-15 12:08
Okay, then this is a duplicate of igraph/rigraph#4 - feel free to add a request for your particular arrow type there.

**Closed by ntamas** 2015-06-15 12:08 UTC
