### ISSUE TITLE
error reading boolean attributes in igraph_cattribute_GAB

### ISSUE THREAD

**Issue by robgjansen** [igraph/igraph#1056] opened 2018-01-27 19:55 UTC
Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] This issue is for the C core of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

I believe that there is an error reading boolean graph attributes in `igraph_cattribute_GAB`. I'm not sure if this also affects boolean vertex and edge attributes.

Reproduce the error as follows. First, create a simple test graphml file using python:
```
import networkx as nx
from cStringIO import StringIO

G = nx.Graph(mybool=True)

s = StringIO()
nx.write_graphml(G, s)

with open('mybool.graphml.xml', 'w') as outf:
    print >>outf, s.getvalue(),

```

the output file produced by the above script is:
```
<?xml version='1.0' encoding='utf-8'?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
  <key attr.name="mybool" attr.type="boolean" for="graph" id="d0" />
  <graph edgedefault="undirected">
    <data key="d0">True</data>
  </graph>
</graphml>
```

Then load the graph using the c core, and try to print the boolean attribute value.
```
// file: testbool.c
// build like: gcc -g -o testbool testbool.c -ligraph

#include <stdio.h>
#include <igraph/igraph.h>

#define FILENAME "mybool.graphml.xml"

igraph_t graph;

int main() {
    igraph_attribute_table_t* oldHandler = igraph_i_set_attribute_table(&igraph_cattribute_table);

    FILE* graphFile = fopen(FILENAME, "r");
    igraph_read_graph_graphml(&graph, graphFile, 0);
    fclose(graphFile);

    if (igraph_cattribute_has_attr(&graph, IGRAPH_ATTRIBUTE_GRAPH, "mybool")) {
        igraph_bool_t value = igraph_cattribute_GAB(&graph, "mybool");
        printf("found boolean value %d\n", value);
    }

    igraph_destroy(&graph);
    return 0;
}
```

The above can be built with `gcc -g -o testbool testbool.c -ligraph`. Running in GDB produces the following output and backtrace:
```
$ gdb testbool
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-100.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /scratch/tor-atlas/test/testbool...done.
(gdb) run
Starting program: /scratch/test/testbool 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff795e0ea in igraph_cattribute_GAB (graph=<optimized out>, name=<optimized out>) at cattributes.c:2225
2225      return VECTOR(*log)[0];
(gdb) bt
#0  0x00007ffff795e0ea in igraph_cattribute_GAB (graph=<optimized out>, name=<optimized out>) at cattributes.c:2225
#1  0x00000000004009af in main () at testbool.c:20
```

Here is some context about my environment. I'm running CentOS 7 with the latest updates.
```
$ uname -a
Linux sol 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ yum info igraph
Installed Packages
Name        : igraph
Arch        : x86_64
Version     : 0.7.1
Release     : 1.el7
Size        : 4.0 M
Repo        : installed
From repo   : epel
Summary     : Library for creating and manipulating graphs
URL         : http://igraph.sourceforge.net/
License     : GPLv2+
Description : igraph wants to be an efficient platform for
            : 1) complex network analysis and
            : 2) developing and implementing graph algorithms.
            : It provides flexible and efficient data structures for graphs and related
            : tasks. It also provides implementation to many classic and new graph
            : algorithms like: maximum flows, graph isomorphism, scale-free
            : networks, community structure finding, etc.
```

My apologies if this has already been fixed, but I didn't notice any closed issues in a quick search on github. Thanks!

**Comment by ntamas** [comment] 2018-01-27 20:16
Not sure, maybe this one is related: https://github.com/igraph/igraph/commit/9d7b824eb7ea5bc2a2c0a50130171bbb454b2874

It is definitely after the release of 0.7.1, i.e. the latest released version of the C library (which was nearly four years ago). I don't know whether it's related to your use-case -- I can check more thoroughly next week.

**Comment by ntamas** [comment] 2018-02-06 11:30
Tested with [libigraph0v5](https://packages.ubuntu.com/artful/libigraph0v5) on Ubuntu -- sorry, I have no access to a Redhat machine here, but the Ubuntu package is supposedly built from the same source and it has no patches in the source that might even remotely be relevant to this issue.

Your code runs just fine on Ubuntu - even Valgrind did not reveal any issues with invalid memory access or leaking memory. So I am inclined to say that this is RHEL-specific. Have you tried compiling igraph from source and then linking to that instead of relying on the RHEL package?

**Comment by robgjansen** [comment] 2018-02-06 14:19
I've worked around this problem locally by just processing "True" as a string value. That is a fine workaround for me, but it seems that in the long term you would want this to work correctly everywhere.

I can try compiling from source if that would help you to debug the issue. Another option would be a virtual machine, which are pretty easy to set up these days.

**Comment by ntamas** [comment] 2019-05-17 12:06
We will add a test case before the release of 0.8.0 that tests your graph as provided in the original description. Hopefully it will be okay and then we can close it.

**Comment by iosonofabio** [comment] 2019-05-21 22:47
Trying to add this test case in PR #1191 - but I'm not sure whether that requires some more files

**Comment by ntamas** [comment] 2019-05-22 07:49
You also need to extend one of the Autotest files in `tests/` (`foreign.at` seems to be the best fit at the moment). This is needed to ensure that `make check` picks up the new test.

Also, maybe we should create a new folder in `examples/` for bug regression tests; say, `examples/regressions/`, and then move all regression tests there. (I think we have a few others). If we don't do this, then the test code itself should go in `examples/tests/`; we have agreed recently that we will try to keep _real_ examples in `examples/simple/` instead of a general dumpyard for examples and tests. (I think you weren't on the mailing list yet so that's why I'm telling you now).

**Comment by vtraag** [comment] 2019-05-22 07:54
Isn't it strange to keep bug tests in `examples/tests/`? Would it be possible to use `tests/bugs/` or `tests/regressions/` for that or would that conflict with autotest? Or would it be possible to include bug tests using autotest?

**Comment by szhorvat** [comment] 2019-05-22 08:07
Yes, the naming is strange, but I think that at this point rearranging all the _existing_ examples and test, and sorting out what is an example, what is a test, and what's both, would be a lot of work for very little practical gain.

Until last week both examples and tests lived in `examples/simple`.  I suggested that for now, newly added tests should go in a separate location, and examples and tests should be treated separately. I asked for this because for `igraph_simplify_and_colorize` I wanted to add _both_ tests and examples. Tests rarely make a good _educational_ example, so I wanted to separate them.  As a quick solution, I put the tests in `examples/tests` instead. There's also `examples/benchmarks`. 

At some point, the directories can be renamed (autotest doesn't mind), but I wouldn't put too much time into it while there are higher priority, more practically relevant issues.

**Comment by vtraag** [comment] 2019-05-22 08:16
OK, fair point. Let's stick to `examples/tests/` then for now.

**Comment by iosonofabio** [comment] 2019-05-23 02:46
Moved files to `examples/tests` and added test to `tests/attributes.at`, right after the similarly named test `Boolean graph attribute bug 2`

**Closed** 2019-06-25 00:44 UTC
