### ISSUE TITLE
igraph_sparsemat_t not updated consistently in a loop?

### ISSUE THREAD

**Issue by advaitb** [igraph/igraph#1247] opened 2019-08-26 21:43 UTC
Hello,

I've been playing around with igraph_sparsemat_t for a while now and am sort of stuck. Below is a minimal reproducible code for my problem. As you can see, I have the (2x2) sparsemat built and am trying to update a certain position (1,1) in a loop. Based on my understanding, the 1,1 index should print 1000 in the last cout statement. But instead it prints 0 as if no update occurred. Is there any way this can be corrected? Or is there another way to do this? I need to build a huge sparsemat by iterating through the edges and this is the only way i figured it was possible.

On the other hand if I remove the loop and copy paste the updates one below the other, it works, which causes me to think there is some reference being messed up in the loop. Outputing the elem variable in the loop after ```igraph_sparsemat_index``` gives me garbage values.

```
extern "C"
{
#include <igraph.h>
}
#include <cstdlib>
#include <cstdio>
#include <iostream>

int main(int argc, char* argv[]){

        igraph_sparsemat_t spmat,cmat;

        igraph_sparsemat_init(&spmat,2,2,1);
        igraph_sparsemat_entry(&spmat,0,0,0);
        igraph_sparsemat_entry(&spmat,0,1,0);
        igraph_sparsemat_entry(&spmat,1,0,0);
        igraph_sparsemat_entry(&spmat,1,1,0);
        igraph_vector_int_t rid,cid;
        igraph_vector_int_init(&rid,1);
        igraph_vector_int_init(&cid,1);
        igraph_real_t elem;
        for(int i=0; i< 1000; ++i){
                igraph_vector_int_set(&rid,0,1);
                igraph_vector_int_set(&cid,0,1);
                igraph_sparsemat_compress(&spmat,&cmat);
                igraph_sparsemat_index(&cmat,&rid,&cid, nullptr, &elem);     
                igraph_sparsemat_entry(&spmat,1,1,elem++);
        }
        igraph_vector_int_set(&rid,0,1);
        igraph_vector_int_set(&cid,0,1);
        igraph_sparsemat_index(&cmat,&rid,&cid, nullptr, &elem);
        cout<<elem<<endl;
}
```
Output:
```
Current: 0
Expected: 1000
```

Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] This issue is for the C core of igraph.
- [ ] This issue is a bug report or a feature request, not a support question.

**Comment by ntamas** [comment] 2019-08-28 02:03
This is not a bug; the following line is incorrect:

```
igraph_sparsemat_entry(&spmat,1,1,elem++);
```

You are using the _postincrement_ operator on `elem`, which means that its value will be evaluated first, and _then_ `elem` will be incremented. In the first iteration, `elem` is zero, so you write zero back into the matrix, and _then_ increment `elem`. In the next iteration, `elem` will be zero again.

**Closed by ntamas** 2019-08-28 02:03 UTC
