### ISSUE TITLE
Edges sometimes connect at the wrong place

### ISSUE THREAD

**Issue by dmurdoch** [igraph/igraph#2455] opened 2023-12-23 10:53 UTC
This is based on a report on SO, here:  https://stackoverflow.com/q/77706337 .

**Describe the bug**
When plotting a graph, some edges don't connect to the near side of a node, they pass through the node and connect to the far side.

**To reproduce**
This is a simplified version of the code from SO:

``` r
library(igraph)
#> 
#> Attaching package: 'igraph'
#> The following objects are masked from 'package:stats':
#> 
#>     decompose, spectrum
#> The following object is masked from 'package:base':
#> 
#>     union
camp <- graph.formula(Harry:Steve:Don:Bert +-+ Harry:Steve:Don:Bert)

V(camp)$label <- V(camp)$name
set.seed(42)   ## to make this reproduceable
co <- layout.auto(camp)

plot(0, type="n", ann=FALSE, axes=FALSE, xlim=extendrange(co[,1]), 
     ylim=extendrange(co[,2]))
plot(camp, layout=co, rescale=FALSE, add=TRUE,vertex.color=adjustcolor("blue",.3),
     vertex.shape="rectangle",
     vertex.size=(strwidth(V(camp)$label) + strwidth("oo")) * 100,
     vertex.size2=strheight("I") * 2 * 100)
```

![](https://i.imgur.com/cJZJoF6.png)

<sup>Created on 2023-12-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The edges from Bert to Steve and Don to Harry show the problem.

**Version information**
This appears both in the CRAN version 1.6.0 and the devel version 1.6.0.9008.

**Comment by ntamas** [comment] 2023-12-23 11:08
Duplicate of igraph/rigraph#501. Please follow the discussion there.

**Closed by ntamas** 2023-12-23 11:08 UTC
