### ISSUE TITLE
Code coverage report creation is broken

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1608] opened 2021-01-16 11:02 UTC
**Describe the bug**
Trying to create a code coverage report results in an error.

**To reproduce**
```
cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DIGRAPH_ENABLE_CODE_COVERAGE=ON
make coverage
```

At the end of the process, I see the error:
```
Finished .info-file creation
Combining tracefiles.
Reading tracefile coverage.base
lcov: ERROR: no valid records found in tracefile coverage.base
make[3]: *** [CMakeFiles/coverage] Error 255
make[2]: *** [CMakeFiles/coverage.dir/all] Error 2
make[1]: *** [CMakeFiles/coverage.dir/rule] Error 2
make: *** [coverage] Error 2
```

**Version information**
45895c7e4a56a64d0efb74aa08bb4e15dc29e927

**Comment by ntamas** [comment] 2021-01-16 17:45
I need more information about how to reproduce it as it works completely fine on my machine; I get something like this:

```
Finished .info-file creation
Combining tracefiles.
Reading tracefile coverage.base
Reading tracefile coverage.capture
Writing data to coverage.total
Summary coverage rate:
  lines......: 66.0% (59964 of 90819 lines)
  functions..: 62.4% (5604 of 8977 functions)
  branches...: no data found
Reading tracefile coverage.total
[...]
```

The `coverage.base` file that you are missing contains ~150K lines in my case.

**Comment by szhorvat** [comment] 2021-01-19 11:25
As discussed in chat:

While a sole `make coverage` did not work, `make` followed by `make coverage` did.

There is now a new wiki page with instructions on how to create coverage reports: https://github.com/igraph/igraph/wiki/Generating-test-coverage-reports

**Comment by ntamas** [comment] 2021-01-19 11:32
Also, for the record: it seems like the CMake version is unrelated; the cause of the issue is that the `.gcno` files that hold structural information about the object files are not present until `make` is called. Furthermore, `make clean` does not clean them up so a `make && make clean && make coverage` sequence gives the false impression that `make coverage` works in a clean build dir while in fact it does not.

Anyway, `make && make coverage` is the way to go so I'm closing this issue.

**Closed by ntamas** 2021-01-19 11:32 UTC
Labels: todo
