### ISSUE TITLE
Test suite failure for i386

### ISSUE THREAD

**Issue by tillea** [igraph/igraph#1894] opened 2021-12-17 07:56 UTC
**Describe the bug**
The Debian packaged version of igraph is checked in some Gitlab CI instance whether it builds properly.  Recently version 0.9.5 was packaged.  It turns out that there is a test suite issue on i386 which can be seen in the [build log](https://salsa.debian.org/med-team/igraph/-/jobs/2286877):

    398: Test timeout computed to be: 1500
    397/398 Test #398: test::igraph_sir ..................................   Passed    0.05 sec
    393: Error at src/misc/feedback_arc_set.c:505 : glp_add_rows: nrs = 114088450; too many rows
    393: Error detected in file api/prob1.c at line 257 - Internal GPLK error.
    398/398 Test #393: test::glpk_error ..................................   Passed    1.97 sec
    99% tests passed, 1 tests failed out of 398
    Total Test time (real) =  17.14 sec
    The following tests did not run:
        364 - test::tls1 (Skipped)
    The following tests FAILED:
        160 - test::igraph_edge_betweenness (Failed)
    Errors while running CTest

**To reproduce**
Hope you can verify the issue by running the build on a i386 machine / emulator / chroot.

**Version information**
Version 0.9.5 - the [build log](https://salsa.debian.org/med-team/igraph/-/jobs/2286877) should present all relevant information.

Kind regards, Andreas.

**Comment by szhorvat** [comment] 2021-12-17 08:12
The failure is in `igraph_edge_betweenness` as:

```
 Testing bug 950, tolerances
-( 0 0 2.33333 2.33333 2.33333 0 2.33333 2.33333 2.33333 2.33333 2.33333 2.33333 0 0 0 )
+( 0 0 1 3 1 0 3 5 3 1 3 1 0 0 0 )
```

This is surprising since this type of failure on i386 is usually due to using x87 math instead of SSE. But we do test on i386 Windows, and we do test explicitly with x87 math on 64-bit Linux. I wonder if Debian somehow ends up using unusual compiler options that affect the rounding behaviour or the order of arithmetic operations.

**Comment by szhorvat** [comment] 2021-12-17 08:17
The build log shows no compiler options that affects arithmetic. The only notable thing is that LTO is enabled. GCC version is 11.2.0.

**Comment by ntamas** [comment] 2021-12-17 08:40
Thanks @tillea for the report and @szhorvat for the quick investigation. I'll set up an i386 machine and try to reproduce it.

**Comment by tillea** [comment] 2021-12-17 08:43
Am Fri, Dec 17, 2021 at 12:40:18AM -0800 schrieb Tamás Nepusz:
> Thanks @tillea for the report and @szhorvat for the quick investigation. I'll set up an i386 machine and try to reproduce it.
Thanks to you guys also from me.  Its very motivating to report issues when the response comes that promptly.  Kind regards, Andreas.

**Comment by ntamas** [comment] 2021-12-17 13:46
Confirmed in a chroot on my own machine, FYI.

**Comment by szhorvat** [comment] 2021-12-17 14:20
@ntamas Things must be going wrong at the call to `igraph_cmp_epsilon`, i.e. the comparison with tolerance. Can you print out the values passed to this function, and identify the difference between the 64-bit and 32-bit cases? I can't fathom why the 32-bit case would be different from 64-bit with x87 math (for which we have tests). 

This can likely be fixed by increasing `IGRAPH_SHORTEST_PATH_EPSILON`, but I want to know why that increase would be necessary only on this platform. I find it very puzzling. I don't have an i386 setup myself.

**Comment by ntamas** [comment] 2021-12-17 15:03
@szhorvat Something with LTO seems to induce the failure; compiling in an i386 chroot without LTO makes the test pass without problems, but it fails with LTO.

**Comment by szhorvat** [comment] 2021-12-17 15:33
@ntamas If it's easy enough, can you try with clang please?

**Comment by ntamas** [comment] 2021-12-17 16:24
This is a heisenbug; adding a print statement around `igraph_cmp_epsilon()` apparently alters the behaviour in a way that the bug is no longer present. Removing `printf` triggers it again.

I can check it with `clang` but I'm not sure what benefit it would bring; Debian's packages are compiled with `gcc` so we need to solve the issue with `gcc`, right?

**Comment by szhorvat** [comment] 2021-12-17 16:57
You're right, it might not help much, but if it also gives bad results, that may be a hint.

I am wondering if this could be a compiler bug. I have been a similar "heisenbug" with the PGI compiler. As soon as I looked at the mishandled piece of data, e.g. with a printf, the bug disappeared. In the end I managed to figure out that it was a compiler bug (somehow it passed in an uninitialised data structure, possibly due to incorrectly reordering instructions).

Shouldn't compilers avoid transformations that change the order of arithmetic operations and thus change the roundoff errors (unless unsafe features are enabled with `-ffast-math` or similar)? Could this be a bug where this is not respected?

I wonder by how much you need to increase `IGRAPH_SHORTEST_PATH_EPSILON` before the problem goes away. I also wonder at what optimization level the problem disappears at. The default is `-O3`. Does it happen at `-O2`, `-O1`?

**Comment by tillea** [comment] 2021-12-17 17:54
Am Fri, Dec 17, 2021 at 08:24:32AM -0800 schrieb Tamás Nepusz:
> This is a heisenbug; adding a print statement around `igraph_cmp_epsilon()` apparently alters the behaviour in a way that the bug is no longer present. Removing `printf` triggers it again.
Argh.
 
> I can check it with `clang` but I'm not sure what benefit it would bring; Debian's packages are compiled with `gcc` so we need to solve the issue with `gcc`, right?
The default compiler is gcc and the issue occured with this compiler.  On the other hand there are people who are working on compiling the archive with clang - so if you would make sure igraph would work with both that would be extra cool but not really necessary for the moment.

Kind regards, Andreas.

**Comment by szhorvat** [comment] 2021-12-17 18:28
Just to have it in the public record, this problem was reproducible on 64-bit as well, if using x87 math (instead of the default SSE) and LTO. I could reproduce it both with GCC 10.2.0 and 9.3.0.

Fix from Tamás is likely incoming very soon ;-)

**Closed** 2021-12-17 18:29 UTC

**Comment by ntamas** [comment] 2021-12-17 18:32
It turned out that it was a genuine bug in `igraph_cmp_epsilon()`; thanks for reporting it! The fix is in the commit linked above, it's only 4 chars :) I'd recommend patching it in Debian until we can make a new release.

With my tests, the bug now seems to be gone in an i386 chroot when compiling with LTO. I'll attempt to run a full package build in the chroot using the Debian tooling, but if you can confirm that the patch works in the meanwhile, that would be great.

Thanks to @szhorvat for helping with tracking this issue down.

**Comment by ntamas** [comment] 2021-12-17 19:08
Hang on, it might be the case that 1031f3d is not the correct patch; still investigating. Another commit might come in a few minutes or at most an hour or so.

**Comment by jgmbenoit** [comment] 2021-12-17 20:37
Thanks for resolving the issue so promptly.

**Comment by szhorvat** [comment] 2021-12-17 20:42
Don't forget to update the changelog @ntamas

**Comment by ntamas** [comment] 2021-12-17 20:52
Done. So, for the Debian package, I'd suggest to meld 1031f3d and 8c5711d into a single patch, which should solve the problem.
