### ISSUE TITLE
Cannot import igraph from pypy3 venv

### ISSUE THREAD

**Issue by gokcedilek** [igraph/igraph#1157] opened 2019-03-15 22:34 UTC
When I try to import igraph from my pypy3 virtual environment, I am getting the following error:

TypeError: 'module' object is not subscriptable
What exactly does this error mean; how could I fix that?

Thank you!

**Comment by ntamas** [comment] 2019-03-16 08:30
Duplicate of igraph/python-igraph#213

**Closed by ntamas** 2019-03-16 08:30 UTC
