### ISSUE TITLE
[Windows] failing tests because of EOL issues

### ISSUE THREAD

**Issue by jannick0** [igraph/igraph#1401] opened 2020-06-08 17:04 UTC
I am compiling the igraph package on Windows using MSYS's MINGW64.  The package compiles fine, but there are two issues with the tests (i.e. when running `make check`):

1. Most of the tests fail because of EOL issues. This can be worked around by using the additional flag `--strip-trailing-cr` passed on to `diff` when running the tests.  This is a remedy for the situation where the tests create files with `CRLF` as EOL (unless the output stream mode is set to binary), while the original test files to be compared with have `LF` as EOL.
2. Given (1.) the remaining tests which fail are pajek-related which call `foreign.c`.  In this file `newline` is set to `\r\n` which on Windows is converted to `\r\r\n` (unless the output stream mode is set to binary which appears not to be the case in the tests at hand):  
https://github.com/igraph/igraph/blob/c8fc07f8e5f51e04dbe47a439792297efca2000d/src/foreign.c#L2094
Now step (1.) removes the latter `\r`, i.e. it converts `\r\r\n` back to `\r\n` which then creates a difference to the original test files due to the additional `\r`.

A potential way out of issue (2.) could be to define in `foreign.c`  `newline` as `\n` on Windows (when, e.g., the macro `_WIN32` is defined).

I did not go deeper into how EOLs are treated in the lexers on various platforms.  

Of course, happy to see other solutions for (1.) without tweaking `diff` flags when running `make check` on a Windows platform.

**Comment by vtraag** [comment] 2020-06-08 18:33
Thanks for the report! Could you please indicate whether you build `igraph` from the provided MSVC zip file, or whether you are building from the cloned GitHub repository? This might be relevant for issue (1).

**Comment by jannick0** [comment] 2020-06-08 19:11
I used [igraph-0.8.2.tar.gz](https://github.com/igraph/igraph/releases/download/0.8.2/igraph-0.8.2.tar.gz). Should I expect Windows-like EOLs in [igraph-0.8.2-msvc.zip](https://github.com/igraph/igraph/releases/download/0.8.2/igraph-0.8.2-msvc.zip)?  That would indeed help then, but I did not try since I was not aware of that if true.

**Comment by vtraag** [comment] 2020-06-08 19:21
OK, thanks!

It seemed somewhat strange to hear you are encountering line ending difficulties, because `igraph` is build in a [CI on Windows](https://ci.appveyor.com/project/ntamas/igraph) using `msys2`, and all tests run correctly. I thought that it might be an issue because of line endings being changed when cloning using `git`, but that is apparently not the case then.

Could you perhaps identify the difference between how you build `igraph` and the setup at the CI? See [`appveyor.yml`](https://github.com/igraph/igraph/blob/master/appveyor.yml) for details.

**Comment by jannick0** [comment] 2020-06-08 19:43
Sure ... I quickly rushed through your `appeyor.yml` which uses the cygwin/unix-like `msys`. However, I am compiling with `msys`s `MINGW64` which is somehow closer to `MSVC`.  The former lives with unix-like EOLs, i.e. `LF`, while the latter usually works with `CRLF`.  I am using the `autoconf` machinery as your `appeyor.yml`.

So the `MINGW64` route reveals some new EOL issues `msys` is not able to see I guess.

**Comment by szhorvat** [comment] 2020-06-08 20:08
> Could you perhaps identify the difference between how you build `igraph` and the setup at the CI? See [`appveyor.yml`](https://github.com/igraph/igraph/blob/master/appveyor.yml) for details.

This is just a hunch, but it may be that git automatically transforms newlines to match the OS's convention. I know it has such a setting. I never changed it. I never tried to use the released tarball to compile with msys2/mingw, I always used git. We should try the tarball.

**Comment by jannick0** [comment] 2020-06-09 07:07
Blindly converting EOLs of all files to `CRLF` on Windows can get you into hot water when you want to run a `bash/shell` script (e.g. `bootstrap.sh` or `configure`); they won't work any more because of stray `CR`s the shell is confused about.

This is why I do not have `git` convert any EOLs, I leave them as they are when cloning a `git` repository.

**Comment by vtraag** [comment] 2020-06-09 07:38
> This is why I do not have `git` convert any EOLs, I leave them as they are when cloning a `git` repository.

That makes sense. I think that @szhorvat means to say that perhaps the CI does do this somehow, which is why we are not seeing the same problem as you. I'll have to find some time to build from the provided source on a Windows machine to check if I can reproduce the problems locally.

**Comment by szhorvat** [comment] 2020-06-09 09:03
> I think that @szhorvat means to say that perhaps the CI does do this somehow, which is why we are not seeing the same problem as you.

Yes, that's what I meant.

----

Today I tried to use the release tarball with msys2, and indeed all tests fail. We don't want separate tarballs for MinGW and Linux/Mac, so we definitely need to find a solution to this.

**Comment by iosonofabio** [comment] 2020-07-07 09:13
Is this still open? We have gone through some overhauling of the windows tests in recent weeks...

**Comment by szhorvat** [comment] 2020-07-07 11:06
Please don't close this yet. The fixes were done only on the cmake branch. Let's see if there's an easy solution that is applicable to the 0.8 series.

**Closed** 2020-08-02 05:24 UTC
Labels: todo
