### ISSUE TITLE
sample_pa: At core/core/psumtree.c:179 : Assertion failed: search < igraph_psumtree_sum(t).

### ISSUE THREAD

**Issue by csqsiew** [igraph/igraph#2186] opened 2022-09-06 10:27 UTC
**Describe the bug**

A strange error message when the power argument is negative in the sample_pa function. 

**To reproduce**

```
> library(igraph)
> set.seed(1)
> g1 <- sample_pa(n=10, power = -1, m = 2) # n = # nodes to grow until, m = # edges to add 
Warning message:
In sample_pa(n = 10, power = -1, m = 2) : `power' is negative

> g2 <- sample_pa(n=20, power = -1, m = 2, start.graph = g1) # use previous graph as the starting graph
Error in sample_pa(n = 20, power = -1, m = 2, start.graph = g1) : 
  At core/core/psumtree.c:179 : Assertion failed: search < igraph_psumtree_sum(t). This is an unexpected igraph error; please report this as a bug, along with the steps to reproduce it.
In addition: Warning message:
In sample_pa(n = 20, power = -1, m = 2, start.graph = g1) :
  `power' is negative
```

**Version information**

 - R/igraph version: 1.3.4
 - R version: 4.2.1
 - Operating system: Ubuntu 22.04

**Comment by szhorvat** [comment] 2022-09-06 11:11
@ntamas Without looking too much at the code, I suspect this has to do with rasing zeros to negative powers, which yields infinities. The starting graph has vertices with zero in-degree.

**Comment by szhorvat** [comment] 2022-09-06 11:16
No, because the formula is not `(degree + zero_appeal) ^ power` but `degree^power + zero_appeal`.

I tested replacing `pow()` by the following at it doesn't crash anymore. But let's not rush this, let's think it through first.

```
static double zpow(double x, double a) {
    return x <= 0 ? 0.0 : pow(x, a);
}
```

**Comment by ntamas** [comment] 2022-09-06 11:18
I guess the easiest would be simply to disallow non-positive exponents completely. @csqsiew is there any specific use-case where you want to use a negative exponent and get a meaningful result, or did you simply expect igraph not to blow up completely when passing a negative exponent to `sample_pa`?

**Comment by szhorvat** [comment] 2022-09-06 11:22
My preference would be the fix from above (except with `x == 0` instead of `x <= 0` in order not to mask any unexpected bugs). This is because I prefer flexibility and the ability to experiment. This is a reasonable generalization of the model.

However, we would need to state very clearly that vertices with degree zero always have `zero_appeal` attractiveness, as the formula `degree^power + zero_appeal` would not apply anymore.  I think this is fine because degrees are integers, not real numbers. There is no way to take a continuous limit towards zero. So a special treatment of zero degrees is fine for as long as it is clearly documented.

**Comment by szhorvat** [comment] 2022-09-06 11:23
I invoke design principles 2 and 3 (which I admit I wrote myself :-) ) https://github.com/igraph/igraph/wiki/Design-principles-for-functions

**Comment by szhorvat** [comment] 2022-09-06 12:07
I thought a bit more about this in the meantime, and it's more complicated than it initially appeared. So I would actually suggest just disallowing negative weights for now, and we can improve this further for 0.10 in the spirit of generality and flexibility.

I'll try to explain my current thoughts in a comment later.

**Comment by szhorvat** [comment] 2022-09-06 12:22
**What's wrong with using `0^power == 0` for all `power`?**

Positive powers mean that vertices with higher degrees have higher attractiveness. Negative powers mean that lower degrees have higher attractiveness. I am not comfortable about making the attractiveness function non-monotonic with respect to the degree, which is what this would do.

**What about using infinite attractiveness for 0-degree vertices when `power < 0`?**

Thus _it would seem_ that it's better to stick to the formula and use infinite attractiveness for 0-degree vertices when `power < 0`. Implementing this would be a bit of a pain, so first let's see if it's worthwhile.

Using this choice implies that when there are zero (in-)degree vertices in the existing graph, newly added vertices are only allowed to connect to these. If we start with a single vertex, as usual, then this model creates a path graph:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/1212871/188631975-ed77c001-f5f5-49eb-b76b-caaeb5d4bba9.png">

This is trivial, and not worth supporting.

What if the starting graph has more than a single vertex, and more than one of them have zero (in-)degree? Again, this case is not very interesting. Multiple path graphs would grow "backwards" from the zero-degree vertices of the starting graph. Supporting this requires even more work—not worth it.

My conclusion is that for the directed version of the model, it is not useful to support negative degrees.

**The undirected case**

But what if `outpref == true`, i.e. attractiveness is calculated based on the total degree instead of the in-degree? With this choice, in most scenarios zero degrees are avoided completely. Indeed, this is the case when `zero_appeal == 0` makes sense. Therefore, it is possible to defined a model with non-trivial behaviour with `power < 0`.

I think this is interesting and worth supporting. But implementing it is not trivial:

 - If we start with a single vertex, initially it will have degree zero. This needs to be handled specially because `psumtree` can't deal with infinities.
 - If we use a graph which has some isolated starting vertices, only these vertices can be connected to until all of them gain some connections.

Implementing this is not trivial, and we don't want anything but absolutely trivial changes for the 0.9 branch. Thus if we implement this, I think it makes sense to only do it for 0.10.

**What about `power == 0`?**

This is again a non-trivial model, which might be worth supporting. Here it makes sense to choose `degree^0 == 1` for all `degree`s, including `degree == 0`. This does not yield inconsistencies with monotonicity. Also, this is quite simple to implement, so it can go in as a fix for 0.9.

**Comment by szhorvat** [comment] 2022-09-06 12:26
Finally, I recommend adding a check to `igraph_psumtree_update()` for positive infinities. It already has a check hat covers negative numbers (including $-\infty$) and NaN.  Additionally, I recommend issuing an informative message from this function instead of just returning an error code with no `IGRAPH_ERROR`.

This will cover any other functions / cases that also uses psumtree and which we may not have thought of.

**Comment by szhorvat** [comment] 2022-09-06 13:34
Sorry, I'm too rushed today. Of course, the first Mathematica example above _shouldn't_ have worked.

One issue here is that the implementation assumes that if `outpref == false` then weight of newly added vertices is always the `A` "zero appeal", not `d^power + A`. See this line specifically:

https://github.com/igraph/igraph/blob/master/src/games/barabasi.c#L417

**Comment by ntamas** [comment] 2022-09-06 13:59
@szhorvat Matrix devs asked for a fix before Sept 8 for the breakages caused by Matrix 1.5. This was sent to me several weeks ago and I've implemented the fixes back then, so ideally there should be at least an igraph 1.3.5 submission before Sept 8. I'd rather not delay that so I'd advocate doing a quick fix here, even if it does not cover all corner cases and generalizations that you can possibly think of.

**Comment by szhorvat** [comment] 2022-09-06 15:01
@ntamas I pushed a fix/refactor on `master`, please take a look. The approach is:

 - Define an attraction function once re-use it, to make sure that the same function is used everywhere
 - Delegate reporting errors to `psumtree_update()`

If it looks good to you, I can backport to 0.9.

**Comment by szhorvat** [comment] 2022-09-06 15:05
@ntamas Alternatively, just disallow negative weights in 0.9  and be done with it. That's completely fine for me, as I don't want to spend time on that version.

**Closed** 2022-09-07 11:04 UTC
