### ISSUE TITLE
Fortran runtime error

### ISSUE THREAD

**Issue by cpfaff** [igraph/igraph#1121] opened 2018-10-17 08:49 UTC
I filed this one first at the rigraph repository. But here seems the right place for it. 

https://github.com/igraph/rigraph/issues/299

**Comment by szhorvat** [comment] 2018-10-17 11:15
Can you produce a minimal example in C, not in R, and then try it with the latest development version of igraph? Some of the involved functions (ARPACK stuff) were updated recently.

(I cannot reproduce the issue in R on a Mac, with the official R and igraph releases.)

**Comment by cpfaff** [comment] 2018-10-17 11:32
And I am not quite sure if I really get what you mean by that minimal example and how to execute it finally in the context of R. Unfortunately I am not a C programmer. Some help with compiling a minimal example in C would be of great help then I guess. 

However I also did not do anything special, or something with own data. The reported issue that I linked in the first post uses one of the minimal examples from the igraph documentation.

**Comment by ntamas** [comment] 2018-10-17 11:55
How did you install igraph in R? Was it simply a matter of running `install.packages("igraph")` or did you compile it yourself?

The reason why I am asking is because the error seems to come from ARPACK. igraph can be compiled with a "built-in" ARPACK library that was translated from Fortran to C a while ago, or it can link to an existing ARPACK installation, and we need to know whether the error message comes from the built-in ARPACK (in which case we can do something about it) or an external ARPACK (in which case it's probably a bug in ARPACK itself).

**Comment by cpfaff** [comment] 2018-10-17 11:58
Ok I see. I installed it by a simple call to `install.packages("igraph")`. In my case it is coming then from the mran repository as I am using the microsoft enhanced R.

**Comment by cpfaff** [comment] 2018-10-17 12:04
I am currently trying to install the dev version using devtools however I guess it does not install the right version. It guess by default it is installing from the "master" branch. This seems not right as that one seems quite old. I guess i have to install from the "dev" branch then. However when I switch over to that one it fails due to sub-modules in the repository. I keep trying to test this out.

**Comment by cpfaff** [comment] 2018-10-17 12:28
I could try of course. But mran does not make a difference. It is a bit wise copy and paste of what is on cran (I guess rsync). The only difference it makes is that you can set a time stamp and it will ensure you are not updating your packages beyond that date. In that way you can ensure consistency. 

So there should be no difference at all. They do not modify or compile themselves they just copy everything.

**Comment by ntamas** [comment] 2018-10-17 12:44
> mran does not make a difference. It is a bit wise copy and paste of what is on cran (I guess rsync)
I'm no expert in R, but it seems like at least on OS X, Microsoft R Open will download the _source code_ (that is indeed a bitwise copy of the source code on CRAN) and then try to compile the extension on its own locally. It also seems that Microsoft R Open ships different (multi-threaded) versions of BLAS and LAPACK, both of which are dependencies of ARPACK. It could be the case that ARPACK shipped with igraph is not compatible with the customized versions of BLAS and LAPACK that come with Microsoft R Open. This is all just a speculation because I cannot compile igraph on my Mac -- the compilation phase bails out with an error and I don't have time now to debug what the problem could be. However, based on this, I'm pretty convinced that Microsoft R Open compiles igraph on its own.

**Comment by ntamas** [comment] 2018-10-20 13:58
Closing issue as this seems to be R-related only. Discussion should continue in igraph/rigraph#299.

**Closed by ntamas** 2018-10-20 13:58 UTC
