### ISSUE TITLE
layout.reingold.tilford does not work with trees mode="in" 

### ISSUE THREAD

**Issue by tonigi** [igraph/igraph#670] opened 2014-08-20 18:52 UTC
As per subject:

```
plot(graph.tree(20),layout=layout.reingold.tilford)
```

works, while...

```
plot(graph.tree(20,mode="in"),layout=layout.reingold.tilford)
```

...doesn't.

**Comment by szhorvat** [comment] 2018-11-16 10:37
Potentially related: https://github.com/igraph/igraph/issues/879

**Comment by iosonofabio** [comment] 2019-05-21 22:28
should this bug be moved to the R repo? It seems like the C interface for `mode` is well documented in `layout.c`, line 941:
```
 * \param mode Specifies which edges to consider when building the tree.
 *   If it is \c IGRAPH_OUT then only the outgoing, if it is \c IGRAPH_IN
 *   then only the incoming edges of a parent are considered. If it is 
 *   \c IGRAPH_ALL then all edges are used (this was the behavior in 
 *   igraph 0.5 and before). This parameter also influences how the root 
 *   vertices are calculated, if they are not given. See the \p roots parameter.
```

**Comment by vtraag** [comment] 2019-05-22 06:58
The bug itself concerns some problems when there are no incoming/outgoing edges I believe.

On a related note, the documentation for `layout.reingold.tilford` in R may be be incomplete. @ntamas, perhaps we should open a specific issue in `rigraph` for the documentation.

**Comment by ntamas** [comment] 2019-05-22 07:41
> The bug itself concerns some problems when there are no incoming/outgoing edges I believe.

Yes; you can probably still reproduce it in C by creating a tree graph with edges pointing _towards_ the root, and then trying to construct a layout with `layout_reingold_tilford()` such that it is configured to follow the _outbound_ edges only. Of course there are no such edges from the root so the layout should not produce anything meaningful, but at least it should not put NaNs in the coordinate matrix.

@vtraag Please do if the documentation is indeed incomplete.

**Comment by iosonofabio** [comment] 2019-06-09 22:58
I'm looking at this, but I'm a bit confused as of what the expectation for this corner case would be (tree "in" but layout "out").

First, the function states it makes the input graph connected by adding (directed?) edges, but that part remains quite obscure to me. Second, the internal function `igraph_i_layout_reingold_tilford` initializes the output matrix to be of size `n_nodes x 2` and then goes on a breath-first search to set the Y coordinates. However, in the example above it seems like all those are `NaN`s, indicating this search fails to traverse the whole tree and leaves chunks of the matrix uninitialized.

Since there are no edges from the specified root in this corner case, all edges are "new" edges generated by the function, so the presence of `NaN`s indicates that edge generation is buggy.

Anyone?

**Comment by ntamas** [comment] 2019-06-10 10:55
> First, the function states it makes the input graph connected by adding (directed?) edges, but that part remains quite obscure to me.

I don't have the implementation in front of me right now, but I think this was related to undirected graphs only; the idea was that if the input graph is undirected, the layout would attempt to construct one tree layout per component and place them next to each other as if the roots of these trees were all connected to a virtual extra node via undirected edges.

For directed graphs, the same idea could be used for weakly connected components; if there are N weakly connected components, you can pick a root from each of those components and then take a virtual node that is connected to each of the roots via directed edges whose direction matches the "mode" parameter of the layout. I have no idea whether this has ever been implemented for directed graphs this way, though.

Personally, I would consider this bug as fixed if we could ensure that there are no NaNs in the final layout matrix that the function returns. It would be great if we could try to do our best to traverse the entire graph even if some of the vertices are not reachable from the seed nodes, but that's not a priority right now.

So, the four cases to test are:

* undirected connected graph -- this should work without any problems
* undirected disconnected graph -- the function should identify the connected components and lay out the components one by one, then place them next to each other
* directed, weakly connected graph -- all nodes reachable from the specified root(s) and directionality should be placed nicely, the rest should be placed "next to" the tree somehow
* directed, disconnected graph -- same as the weakly connected case

A final algorithm could do something like this:

1. Initially, no vertices are laid out yet
2. Take the first root given by the user that we have not laid out yet. If there are no such roots, take an arbitrary vertex that we have not laid out yet (or take the one with the highest out-degrees for out-trees and the highest in-degree for in-trees)
3. Find all the nodes reachable from the root and lay them out in a tree
4. Place the tree next to any other trees that we have laid out
5. If there are any unplaced vertices, go back to step 2

**Comment by iosonofabio** [comment] 2019-07-16 23:22
Hey, I'm adding CI tests for this, but the code should be roughly ready. Anyone has a minute to review the PR and give some comments?

**Comment by iosonofabio** [comment] 2019-08-15 18:54
Ok, after a number of further iterations, I think the code should be decent now. If you give it a directed tree with `mode` set to the opposite of the direction of the tree, it splays it out into a line, which is an ok (though not great) layout for that kind of corner case.

This passes local tests on my machine, CI is running

**Comment by iosonofabio** [comment] 2019-08-18 18:22
Fixed, closing

**Closed by iosonofabio** 2019-08-18 18:22 UTC
Labels: confirmed, high
