### ISSUE TITLE
0.9.1: SONAME in the shared library is probably wrong

### ISSUE THREAD

**Issue by yurivict** [igraph/igraph#1749] opened 2021-04-02 10:54 UTC
The plist changed against 0.8.5:
```
-lib/libigraph.a
 lib/libigraph.so
 lib/libigraph.so.0
-lib/libigraph.so.0.0.0
```
lib/libigraph.so.0 has SONAME=libigraph.so.0

Normally SONAME should be shorter than the library filename, so that there is space left for updates without the need to rebuild dependencies. For example:
```
lrwxr-xr-x    1 root  wheel         26 Feb 25 14:47 libzita-convolver.so -> libzita-convolver.so.4.0.3
lrwxr-xr-x    1 root  wheel         26 Feb 25 14:47 libzita-convolver.so.4 -> libzita-convolver.so.4.0.3
-rwxr-xr-x    1 root  wheel      27032 Feb 25 14:47 libzita-convolver.so.4.0.3
```
has SONAME=libzita-convolver.so.4

In case of ```libigraph.so.0``` SONAME is the same as file name.

**Comment by ntamas** [comment] 2021-04-02 19:07
We have switched from `autotools` to CMake between 0.8.5 and 0.9.0; it could be the case that CMake is doing something differently. I'll look into this.

Also note that if you need _both_ a shared and a static library, then you need to build them separately with CMake. Setting `BUILD_SHARED_LIBS` to `ON` will build shared libraries _only_; setting it to `OFF` will build static libraries _only_. That's why you are probably missing `lib/libigraph.a`.

**Comment by yurivict** [comment] 2021-04-02 19:18
> We have switched from autotools to CMake between 0.8.5 and 0.9.0; it could be the case that CMake is doing something differently. I'll look into this.

IMO you should restore the set of *.so* files that existed before.

As to the static library:
* cmake is definitely able to create both at the same time
* but: static libs aren't needed by virtually all users, we usually turn them off for packaging.

**Comment by ntamas** [comment] 2021-04-02 19:22
Okay, the missing `libigraph.so.0.0.0` file is caused by this line in `src/CMakeLists.txt`:

```
set_target_properties(igraph PROPERTIES SOVERSION 0)
```

Apparently this prevents CMake from falling back to the project version when it tries to figure out the "real" version number of `libigraph.so`. It could be fixed as follows, which would then create `libigraph.so.0.9.1` and make `libigraph.so.0` only a symlink to it:

```diff
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index a3174078d..168851bc2 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -288,6 +288,7 @@ add_library(
 )

 # Set soname for the library
+set_target_properties(igraph PROPERTIES VERSION ${PACKAGE_VERSION_BASE})
 set_target_properties(igraph PROPERTIES SOVERSION 0)

 # Add extra compiler definitions if needed
```

Now, the problem is that I looked around in Debian and Ubuntu to see how they handle this. Debian Buster packages igraph 0.7.x and they have `libigraph.so.0.0.0`, symlinked by `libigraph.so.0`. Ubuntu  packages igraph 0.8.2 and they have `libigraph.so.1.0.0`, symlinked by `libigraph.so.1`. For me the logical structure would be this:

```
libigraph.so.0.9.1
libigraph.so.0 --> libigraph.so.0.9.1
libigraph.so --> libigraph.so.0
```

**Comment by ntamas** [comment] 2021-04-02 19:23
> cmake is definitely able to create both at the same time

Can you point me to some documentation about that? We have actually tried to achieve this when we initally did the switch from `autotools` to CMake, but we couldn't achieve it without specifying two targets and making CMake do the compilation twice.

**Comment by yurivict** [comment] 2021-04-02 19:39
> Can you point me to some documentation about that?

Not a documentation, but a description:
https://stackoverflow.com/questions/2152077/is-it-possible-to-get-cmake-to-build-both-a-static-and-shared-version-of-the-sam

**Comment by ntamas** [comment] 2021-04-02 19:50
The first comment on that SO question claims that all the answers are wrong ([blog post](https://alexreinking.com/blog/building-a-dual-shared-and-static-library-with-cmake.html)); I haven't read it in detail yet but it looks like the situation is more complex than what I anticipated. Anyway, we'll definitely fix the problem with the SONAME soon, and we can return to the problem of static libraries later (as you mentioned, you turn them off for packaging anyway).

**Comment by yurivict** [comment] 2021-04-02 20:00
I never tried this myself, but in order to build both static and shared libraries each module should be compiled twice due to different options.

If this doesn't work - then this is likely a make bug.

**Comment by szhorvat** [comment] 2021-04-02 20:10
> > cmake is definitely able to create both at the same time
> 
> Can you point me to some documentation about that? We have actually tried to achieve this when we initally did the switch from `autotools` to CMake, but we couldn't achieve it without specifying two targets and making CMake do the compilation twice.

Let's not try to do this right now. There are some complications that need to be dealt with. For example, the headers are currently different for the two cases (because of symbol visibility declarations / dllexport on Windows).

**Comment by yurivict** [comment] 2021-04-02 21:40
The SONAME numbers aren't supposed to be zeros either.
The minimal working configuration is
libxx.so.{major}.{minor} with ```SONAME=libxx.so.{major}```
```minor``` should be bumped when non-breaking changes are made (ex. incremental changes in the API), ```major``` should be bumped when breaking changes are made and dependencies need to be rebuilt.

**Comment by ntamas** [comment] 2021-04-03 13:03
For the time being I restored the old behaviour as suggested [here](https://github.com/igraph/igraph/issues/1749#issuecomment-812674100) so we now have `libigraph.so.0.0.0` again. There is an internal discussion going on between the developers about how to proceed with the SONAME numbers. We have used zero so far to indicate that we have not committed ourselves to a stable ABI yet; eventually we will as we are nearing version 1.0.0, but there are definitely a few ABI-breaking (and even API-breaking) changes in the pipeline until then, coming up in the next few weeks. The plan is to start from SONAME version 1.0 when igraph 1.0.0 is released.

**Comment by jgmbenoit** [comment] 2021-04-11 09:18
There is different way to managed SONAME triplet, namely the library version. I would recommend the one used in GSL. You may have a look [here](https://autotools.io/libtool/version.html). Concerning Debian, as the ABI from 0.8 to 0.9 is incompatible, I bump SONAME from 1 to 2 .

**Comment by yurivict** [comment] 2021-06-11 00:40
ping.

**Comment by jgmbenoit** [comment] 2021-08-10 06:14
ping

**Comment by ntamas** [comment] 2022-07-22 16:29
Okay, so as we are nearing 0.10.0 it's worth looking at this issue again and decide how this should be handled.

The state of things are as follows:

* 0.10.0 is going to be an API- and ABI-breaking change for sure; in particular, we are adding support for 64-bit integers and there will be an option to compile igraph with 32-bit integers or 64-bit integers. Internally, this controls the size of the `igraph_integer_t` data structure, which is in turn behind pretty much everything in a graph (vertex indices, edge indices etc). I don't know how distros plan to handle this; I'd say that since the goal of igraph is to enable the analysis of large in-memory graphs, it would be preferable to make `igraph_integer_t` as large as possible -- it should probably be 64-bit even on 32-bit Linux distros.
* We wanted to commit ourselves to fixing as many API/ABI-breaking problems in 0.10.0 as possible, but it looks like there are still a few things that need to be sorted out in a later release, so there will probably be a 0.11.0, which breaks the API here and there again, and maybe also breaks the ABI, but the breakage will be not as extensive as in 0.10.0. Nevertheless, breakage is breakage.
* After 0.11.0, we really hope that we can settle the API for the foreseeable future and release a version 1.0.0 with a declared stable API / ABI.

I'm not sure how this will sync up with SONAMEs at all. If I understand correctly from the document linked by @jgmbenoit , SONAMEs do not have to be in sync with the version number of the library at all. Considering that igraph is already being packaged in distros, currently with a SONAME triplet of 0.0.0, I guess that the SONAME of 0.10.0 should become 1.0.0 now (or 1.1.1? Shall we increase all components? That's not clear to me from the docs), and the SONAME of 0.11.0 will have to be 2.0.0 (or 2.2.2?).

**Comment by szhorvat** [comment] 2022-07-22 17:13
> it would be preferable to make `igraph_integer_t` as large as possible -- it should probably be 64-bit even on 32-bit Linux distros.

It makes no sense to make `igraph_integer_t` larger than `ptrdiff_t` / `size_t`. It brings no benefits, just the possibility of overflow.

**Comment by szhorvat** [comment] 2022-07-22 17:28
I was wrong in stating that using a 64-bit `igraph_integer_t` on 32-bit platforms would risk overflow. However, it is still a bad idea to try to do that. It brings only problems, and carried zero advantages.

 - It won't work on most 32-bit platforms anyway, as compiling with a 64-bit `igraph_integer_t` requires a 128-bit integer type. Most 32-bit platforms don't have this.
 - The point of 64-bit integers is to be able to address larger memory areas, but with a 32-bit `size_t` this is not possible anyway.
 - Using an over-large integer type wastes memory on a platform where addressable memory is already at a premium (max 4 GB, or even just 2 GB).
 - Performance penalty due to no 64-bit hardware arithmetic on many 32-bit platforms.

Just leave it at the default, which is to match `size_t`.

**Comment by jgmbenoit** [comment] 2022-07-22 18:03
I have just looked again the `configure.ac` of the [GSL library](https://www.gnu.org/software/gsl/). The header contains a link to a document on [Updating library version information](https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html). I went through the six points: the `c:r:a` should move from `0:0:0` to `1:0:0`. On Debian, I will move from `2:0:0` to `3:0:0` along the same rule. I would suggest to ``synchronize'' (or make things compatible) with other (major) distributions sooner or later but before version `1.0.0`. The sooner the better, I guess. Having an history as in the aforementioned `configure.ac` makes things clear.

**Comment by ntamas** [comment] 2022-07-22 22:55
Got it, and it seems a bit more logical now than before :) So yes, `current:revision:age` will go from `2:0:0` to `3:0:0` in Debian with the release of 0.10. Ubuntu seems to use the Debian packages so nothing to change there. Fedora [seems to use `libigraph.so.0*`](https://src.fedoraproject.org/rpms/igraph/blob/rawhide/f/igraph.spec#_75). Gentoo [also seems to roll with the defaults we have in CMakeLists.txt](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-libs/igraph/igraph-0.9.4.ebuild). I'd say we can start doing things the right way from 0.10.0 by bumping `current:revision:age` to `3:0:0` as Debian is far ahead of the pack.

**Comment by ntamas** [comment] 2022-07-22 23:01
Note to ourselves: [this page](https://cmake.org/cmake/help/latest/prop_tgt/VERSION.html#prop_tgt:VERSION) documents how CMake handles the `VERSION` and `SOVERSION` properties of a library target; if my understanding is correct `SOVERSION` becomes the `current` part in Linux and `VERSION` is parsed as a `current:revision:age` triplet. On macOS, `SOVERSION` is the _compatibility version_ and `VERSION` is the _current version_, so we might need to handle these properties separately. On Windows, `SOVERSION` is ignored and `VERSION` is parsed into a major-minor pair, but I don't think it's too relevant on Windows anyway.

**Comment by szhorvat** [comment] 2022-07-26 11:15
Is anyone in this thread aware of a clear description of how these various dynamic library versions are used on various systems?

Which are the tools that actually look at the version number and make a decision based on it that affects functionality?  Will the dynamic linker check the compatibility version and decide whether the library can be loaded? What are the differences between Linux, macOS and Windows?

**Comment by ntamas** [comment] 2022-07-26 11:27
> Which are the tools that actually look at the version number and make a decision based on it that affects functionality?

On Linux, when building / linking an app that depends on a library, the linker will take the `SONAME` from the library that the app is being linked to and writes its name in a `NEEDED` entry in the binary. This is then later used during app startup to find a compatible library on the library path.

E.g.:

```
~ ❯ objdump -p /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.10 | grep SONAME
  SONAME               libxml2.so.2
```

This indicates that `libxml2.so.2.9.10` has a `SONAME` of `libxml2.so.2`, where the `2` comes from the `SOVERSION` that we specify in `CMakeLists.txt`. If you inspect an app that depends on `libxml2`, you'll see that it has a reference to the same `SONAME`:

```
~ ❯ objdump -p /usr/bin/xmllint | grep NEEDED
  NEEDED               libxml2.so.2
  NEEDED               libc.so.6
```

A similar mechanism exists on macOS, but you'll need to use `otool -L` to get the version numbers:

```
❯ otool -L /usr/bin/xmllint
/usr/bin/xmllint:
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.120.1)
```

For some reason I cannot find `/usr/lib/libxml2.2.dylib` - I guess that Apple's System Integrity Protection prevents the user from messing with system libraries and the real location is somewhere else.

I cannot comment on Windows.

**Comment by jgmbenoit** [comment] 2022-07-26 11:30
On Debian, libraries with different SONAME can coexists. This ease transitions.

**Comment by jgmbenoit** [comment] 2022-07-26 11:46
I would add that we can implement mechanisms in the C[/C++] source that allows to check if the library version actually loaded is compatible with the one against which the software was built. This is easy to implement and this very useful.
I will try to find some relevant examples (that I will post later).

**Comment by yurivict** [comment] 2022-07-26 16:53
SONAME is used during port updates.

When SONAME changes all dependencies need to be updated. But when SONAME doesn't change but only the minor digits in the shared library version change - there is no need to update dependencies.

You don't have minor digits at all, so SONAME becomes dysfunctional for the above purpose.

Functional SONAME is very important for health of the ports. Could you please add conventionally versioned lib/libigraph.so.A.B.C and maintain SONAME?

**Comment by jgmbenoit** [comment] 2022-07-26 19:03
> Could you please add conventionally versioned lib/libigraph.so.A.B.C and maintain SONAME?

On Linux, the current `cmake` configuration does the job.

**Comment by yurivict** [comment] 2022-07-26 19:16
> On Linux, the current cmake configuration does the job.

It does. But all digits are zeros - you need to set and maintain these digits.

**Comment by jgmbenoit** [comment] 2022-07-26 19:23
This is the object to this thread and it was [fixed](https://github.com/igraph/igraph/commit/48a3f280dec3e33729b64facb5a79ff35f2aa459).

**Comment by szhorvat** [comment] 2022-07-26 19:35
> you need to set and maintain these digits.

Yes, that was the idea, to manually update the number for each release. Now let's just hope that we won't forget ...

**Comment by yurivict** [comment] 2022-07-26 19:41
The minor version should be updated with each release that doesn't break API (minor or incremental changes). The major version should be updated when changes are not backward compatible.

**Comment by jgmbenoit** [comment] 2022-07-26 20:32
The full story is available [here](https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html). Most importantly it was followed.

**Comment by szhorvat** [comment] 2022-07-26 20:55
When a shared library is named as `name.so.x.y.z`, which of `x`, `y` and `z` is current, revision and age? `x` is current, but is age `y` or `z`?

**Comment by szhorvat** [comment] 2022-07-26 20:56
@yurivict Is any of this different on BSD in some way that we should be aware of? Does BSD use these numbers in any way that Linux doesn't?

**Comment by yurivict** [comment] 2022-07-26 21:42
> Is any of this different on BSD in some way that we should be aware of? Does BSD use these numbers in any way that Linux doesn't?

No. All of this is common across all distros.

**Comment by yurivict** [comment] 2022-07-26 21:45
> When a shared library is named as name.so.x.y.z, which of x, y and z is current, revision and age? x is current, but is age y or z?

SONAME can be either name.so.x or name.so.x.y.

The remainder is considered to be a minor version.

During incremental or insignificant API updates only the minor version should be bumped. During major API changes major version should be bumped.

**Comment by jgmbenoit** [comment] 2022-07-26 21:47
My understanding is that the dot-triplet is managed by libtool and it takes different form on Linux, Solaris, BSD, etc

**Comment by yurivict** [comment] 2022-07-26 21:49
@jgmbenoit No, it doesn't take different form on Linux, Solaris, BSD AFAIK.

**Comment by jgmbenoit** [comment] 2022-07-26 21:50
> During incremental or insignificant API updates only the minor version should be bumped. During major API changes major version should be bumped.
We are going in circle here. How do you define major and minor versions with respect to current, age, revision ? Are you refering to the major, minor, and nano (patch) versions of the library ?

**Comment by jgmbenoit** [comment] 2022-07-26 21:52
@yurivict  I am dealing with the x.y.z triplet not with the c:r:a triplet (the one passed to libtool)

**Comment by yurivict** [comment] 2022-07-26 21:53
The numbers that are included in SONAME are major numbers, the remainder numbers are minor numbers.

**Comment by yurivict** [comment] 2022-07-26 21:54
> I am dealing with the x.y.z triplet not with the c:r:a triplet (the one passed to libtool)

Exactly. These are the numbers.

**Comment by jgmbenoit** [comment] 2022-07-26 21:55
Which numbers ?

**Comment by jgmbenoit** [comment] 2022-07-26 22:04
[How are shared libraries really versioned on Linux?](https://unix.stackexchange.com/questions/581863/how-are-shared-libraries-really-versioned-on-linux)
[TLDP Howto on Shared Libraries](https://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html).

**Comment by yurivict** [comment] 2022-07-26 22:11
> Which numbers ?

x y z

**Comment by jgmbenoit** [comment] 2022-07-26 22:28
I keep talking about libtool  which is used with autotools suite. But the real issue is how

set_target_properties(igraph PROPERTIES VERSION "3.0.0")

is actually digested and interpreted by `cmake`. And if `libtool` is actually involved.

**Comment by yurivict** [comment] 2022-07-26 22:39
cmake doesn't use libtool.

**Comment by ntamas** [comment] 2022-07-27 09:35
I can confirm, `libtool` is not involved and the `VERSION` property of the library is used as-is in the output filename, i.e. `VERSION 3.4.7` would mean that the library would be named `libsomething.so.3.4.7`. _Inside_ the library, the SONAME that is embedded is a concatenation of `lib`, the library name itself, `.so`, and the value of the `SOVERSION` property -- so, in igraph's case, it would _now_ be `libigraph.so.3`, which I believe is correct.

Just to document this for ourselves: when building with `libtool`, the `current:revision:age` triplet is mapped into the suffix of the filename as `(current-age).age.revision`. This is a major source of confusion. CMake does _not_ do any such magic in the `VERSION` property -- whatever is passed there gets written into the filename.

**Closed** 2022-08-15 15:18 UTC
Labels: todo
