### ISSUE TITLE
layout.reingold.tilford places two nodes on the same position

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#465] opened 2013-05-04 19:00 UTC
In some historical version of igraph (newest in january 2011), the following simple graph was drawn correctly:

 m <- matrix(c(0,0,1,1,0, 0,0,0,1,0, 0,0,0,0,0, 0,0,0,0,0, 0,0,1,1,0), nrow=5)
 g <- graph.adjacency(m)
 plot(g, layout=layout.reingold.tilford)

Igraph version 0.6 places vertices "3" and "4" on the same coordinates:

> layout.reingold.tilford(g)
     [,1] [,2]
[1,]   -1    0
[2,]    0    0
[3,]    0    1
[4,]    0    1
[5,]    1    0

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2012-10-15T19:15:26Z
 * owner: michal-burda
 * the launchpad url was https://bugs.launchpad.net/bugs/1067024

**Comment by szhorvat** [comment] 2015-10-06 10:00
#879 is a duplicate of this.

**Comment by ntamas** [comment] 2015-10-06 10:06
#879 is more detailed so I'm closing this instead.

**Closed by ntamas** 2015-10-06 10:06 UTC
Labels: New
