### ISSUE TITLE
0.9.2: compile time warnings

### ISSUE THREAD

**Issue by kloczek** [igraph/igraph#1761] opened 2021-04-14 14:31 UTC
```console
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/centrality/prpack/prpack_solver.cpp:512: warning: ignoring '#pragma omp parallel' [-Wunknown-pragmas]
  512 |         #pragma omp parallel for firstprivate(c) reduction(+:err, num_es_touched) schedule(dynamic, 64)
      |
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/centrality/prpack/prpack_solver.cpp:539: warning: ignoring '#pragma omp parallel' [-Wunknown-pragmas]
  539 |     #pragma omp parallel for reduction(+:num_es_touched) schedule(dynamic, 64)
      |
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/centrality/prpack/prpack_solver.cpp:682: warning: ignoring '#pragma omp parallel' [-Wunknown-pragmas]
  682 |                 #pragma omp parallel for firstprivate(c) reduction(+:err, num_es_touched) schedule(dynamic, 64)
      |
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/isomorphism/bliss/partition.cc: In member function 'bliss::Partition::Cell* bliss::Partition::zplit_cell(bliss::Partition::Cell*, bool)':
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/isomorphism/bliss/partition.cc:967:22: warning: unused variable 'sorted' [-Wunused-variable]
  967 |           const bool sorted = shellsort_cell(cell);
      |                      ^~~~~~
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/centrality/prpack/prpack_base_graph.cpp: In member function 'void prpack::prpack_base_graph::read_smat(FILE*, bool)':
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/centrality/prpack/prpack_base_graph.cpp:170:12: warning: unused variable 'ignore' [-Wunused-variable]
  170 |     double ignore = 0.0;
      |            ^~~~~~
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/io/pajek-parser.y:105.1-12: warning: deprecated directive: '%pure-parser', use '%define api.pure' [-Wdeprecated]
  105 | %pure-parser
      | ^~~~~~~~~~~~
      | %define api.pure
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/io/pajek-parser.y:108.1-30: warning: deprecated directive: '%name-prefix="igraph_pajek_yy"', use '%define api.prefix {igraph_pajek_yy}' [-Wdeprecated]
  108 | %name-prefix="igraph_pajek_yy"
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | %define api.prefix {igraph_pajek_yy}
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/io/pajek-parser.y/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/io/lgl-parser.y:111.1:68-14: .1warning: -12deprecated directive: '%error-verbose', use '%define parse.error verbose':  [-Wdeprecatedwarning:]
   111 | deprecated directive: '%pure-parser', use '%define api.pure'%e [rr-Wdeprecatedor]-v
erbose
      | ^~~~~~~~~~~~~~
      | %define parse.error verbose
   68 | %pure-parser
      | ^~~~~~~~~~~~
      | %define api.pure
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/io/lgl-parser.y:71.1-28: warning: deprecated directive: '%name-prefix="igraph_lgl_yy"', use '%define api.prefix {igraph_lgl_yy}' [-Wdeprecated]
   71 | %name-prefix="igraph_lgl_yy"
      | ^~~~~~~~/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/io/dl-parser.y~:73~.1~-12~: ~warning:~ ~deprecated directive: '%pure-parser', use '%define api.pure'~ [~-Wdeprecated~]~
~~~~~~~~~
      |    73 | %define api.prefix {igraph_lgl_yy}%
pure-parser
      | ^~~~~~~~~~~~
      | %define api.pure
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/io/lgl-parser.y:74.1-14: /home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/io/dl-parser.ywarning::76 .1-27deprecated directive: '%error-verbose', use '%define parse.error verbose':  [warning: -Wdeprecateddeprecated directive: '%name-prefix="igraph_dl_yy"', use '%define api.prefix {igraph_dl_yy}'] [
-Wdeprecated]
   74 |    76 | %%nearmreo-rpr-evfeirxb=o"sieg
r      | a^p~h~_/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/io/gml-parser.y~d:81~l.1~_-12~y: ~ywarning:~" ~
deprecated directive: '%pure-parser', use '%define api.pure'~      |  [~^-Wdeprecated~~]~
~~~
~~      | ~%define parse.error verbose~
~~~~~~~~~~~~~~~~~~
      |    81 | %define api.prefix {igraph_dl_yy}%
pure-parser
      | /home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/io/dl-parser.y^:79~.1~-14~: ~warning:~ ~deprecated directive: '%error-verbose', use '%define parse.error verbose'~ [~-Wdeprecated~]~
~
   79 |       | %%define api.puree
rror-verbose
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/io/gml-parser.y      | :84^.1~-28~: ~warning:~ ~deprecated directive: '%name-prefix="igraph_gml_yy"', use '%define api.prefix {igraph_gml_yy}'~ [~~-Wdeprecated~]~
~~~   84 |
%      | n%define parse.error verbosea
me-prefix="igraph_gml_yy"
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | %define api.prefix {igraph_gml_yy}
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/io/gml-parser.y:87.1-14: warning: deprecated directive: '%error-verbose', use '%define parse.error verbose' [-Wdeprecated]
   87 | %error-verbose
      | ^~~~~~~~~~~~~~
      | %define parse.error verbose
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/io/pajek-parser.y: warning: 6 shift/reduce conflicts [-Wconflicts-sr]
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/io/pajek-parser.y: note: rerun with option '-Wcounterexamples' to generate conflict counterexamples
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/io/dl-parser.y: warning: 20 shift/reduce conflicts [-Wconflicts-sr]
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/io/dl-parser.y: warning: 3 reduce/reduce conflicts [-Wconflicts-rr]
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/io/dl-parser.y: note: rerun with option '-Wcounterexamples' to generate conflict counterexamples
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/io/ncol-parser.y:69.1-12: warning: deprecated directive: '%pure-parser', use '%define api.pure' [-Wdeprecated]
   69 | %pure-parser
      | ^~~~~~~~~~~~
      | %define api.pure
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/io/ncol-parser.y:72.1-29: warning: deprecated directive: '%name-prefix="igraph_ncol_yy"', use '%define api.prefix {igraph_ncol_yy}' [-Wdeprecated]
   72 | %name-prefix="igraph_ncol_yy"
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | %define api.prefix {igraph_ncol_yy}
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/io/ncol-parser.y:75.1-14: warning: deprecated directive: '%error-verbose', use '%define parse.error verbose' [-Wdeprecated]
   75 | %error-verbose
      | ^~~~~~~~~~~~~~
      | %define parse.error verbose
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/io/lgl-parser.y: warning: fix-its can be applied.  Rerun with option '--update'. [-Wother]
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/io/gml-parser.y: warning: fix-its can be applied.  Rerun with option '--update'. [-Wother]
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/io/ncol-parser.y: warning: fix-its can be applied.  Rerun with option '--update'. [-Wother]
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/io/dl-parser.y: warning: fix-its can be applied.  Rerun with option '--update'. [-Wother]
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/io/pajek-parser.y: warning: fix-its can be applied.  Rerun with option '--update'. [-Wother]
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/x86_64-redhat-linux-gnu/src/io/parsers/dl-lexer.c:2065:24: warning: 'yy_fatal_error' defined but not used [-Wunused-function]
 2065 | static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
      |                        ^~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/x86_64-redhat-linux-gnu/src/io/parsers/gml-lexer.c:1919:24: warning: 'yy_fatal_error' defined but not used [-Wunused-function]
 1919 | static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
      |                        ^~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/x86_64-redhat-linux-gnu/src/io/parsers/ncol-lexer.c:1865:24: warning: 'yy_fatal_error' defined but not used [-Wunused-function]
 1865 | static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
      |                        ^~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/x86_64-redhat-linux-gnu/src/io/parsers/lgl-lexer.c:1869:24: warning: 'yy_fatal_error' defined but not used [-Wunused-function]
 1869 | static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
      |                        ^~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/x86_64-redhat-linux-gnu/src/io/parsers/pajek-lexer.c:2314:24: warning: 'yy_fatal_error' defined but not used [-Wunused-function]
 2314 | static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
      |                        ^~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/hrg/hrg_types.cc: In member function '__ct_base ':
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/hrg/hrg_types.cc:2652:34: warning: argument 1 value '18446744073709551615' exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
 2652 |     splitlist = new string [q + 1];
      |                                  ^
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/hrg/hrg_types.cc:2652:34: note: in a call to built-in allocation function 'operator new []'
In member function '__dt_base ',
    inlined from '__ct ' at /home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/games/degree_sequence_vl/gengraph_graph_molloy_hash.cpp:119:30,
    inlined from 'igraph_degree_sequence_game_vl' at /home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/games/degree_sequence_vl/gengraph_mr-connected.cpp:143:9:
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/games/degree_sequence_vl/gengraph_degree_sequence.cpp:54:18: warning: 'operator delete []' called on pointer '_667' with nonzero offset 8 [-Wfree-nonheap-object]
   54 |         delete[] deg;
      |                  ^
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/games/degree_sequence_vl/gengraph_degree_sequence.cpp: In function 'igraph_degree_sequence_game_vl':
/home/tkloczko/rpmbuild/BUILD/igraph-0.9.2/src/games/degree_sequence_vl/gengraph_graph_molloy_optimized.cpp:200:36: note: returned from 'operator new []'
  200 |     int *hc = new int[2 + n + a / 2]; // to store n,a,deg[] and links[]
      |                                    ^
```

**Comment by szhorvat** [comment] 2021-04-14 14:49
Is there any particular reason you are concerned about these warnings? At a glance they can be safely ignored.

Is there any practical problem you are encountering with igraph? If yes, please elaborate, and show a reproducible example that demonstrates the problem.

**Comment by ntamas** [comment] 2021-04-14 14:51
Lots of unrelated warnings here; as far as I know none of them are harmful, but let's go through the list one by one:

```
src/centrality/prpack/prpack_solver.cpp:512: warning: ignoring '#pragma omp parallel' [-Wunknown-pragmas]
```

It looks like we might have to enable OpenMP pragmas separately for the compiler that you are using; which compiler is that?

```
src/isomorphism/bliss/partition.cc:967:22: warning: unused variable 'sorted' [-Wunused-variable]
src/centrality/prpack/prpack_base_graph.cpp:170:12: warning: unused variable 'ignore' [-Wunused-variable]
```

These are harmless; these variables are used in assertions, which are optimized away by the compile due to `-NDEBUG`. @szhorvat, shall we replace this with `IGRAPH_ASSERT` so they are not optimized away?

```
src/io/pajek-parser.y:105.1-12: warning: deprecated directive: '%pure-parser', use '%define api.pure' 
```

Unfortunately we cannot do anything by this; we need to support macOS, which comes with an old version of Flex and Bison where these are not deprecated and the proposed replacement is not supported yet. This applies to all the other deprecated directives in Flex and Bison files as well.

```
src/io/parsers/dl-lexer.c:2065:24: warning: 'yy_fatal_error' defined but not used [-Wunused-function]
```

I'll remove the declarations of `yy_fatal_error` and check whether it still passes CI.

```
src/hrg/hrg_types.cc:2652:34: warning: argument 1 value '18446744073709551615' exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
```

@szhorvat Isn't this familiar? I think we have seen it in another build log that you showed to me, but I have no idea where it is coming from, especially the "argument 1 value". Could this be a compiler bug? Note that this comes from the following line:

```
splitlist = new string [q + 1];
```

In this line, `q` is not constant so I have no idea how the compiler came up with `18446744073709551615`

**Comment by szhorvat** [comment] 2021-04-14 14:55
> Unfortunately we cannot do anything by this; we need to support macOS, which comes with an old version of Flex and Bison

I think the old Bison in macOS might support `%define api.pure` (I checked the other day), but some of the other warnings can't be fixed without breaking compatibility with macOS's default Bison.

**Comment by ntamas** [comment] 2021-04-14 14:57
> src/io/parsers/dl-lexer.c:2065:24: warning: 'yy_fatal_error' defined but not used [-Wunused-function]

Actually, this is generated by Flex or Bison itself. it is indeed not used, but the best we can do is to turn off the `-Wunused-function` warning for the generated parsers / lexers.

**Comment by szhorvat** [comment] 2021-04-14 14:58
> @szhorvat Isn't this familiar? I think we have seen it in another build log that you showed to me,

Yes, I've seen this in Fedora's build logs. The compiler was a not-yet-released GCC 11.0. I tried to reproduce it with `gcc-devel @11-20210328` from MacPorts, but couldn't. Possibly Fedora is doing something else that triggers this? Possibly it's a bug in the beta compiler? Either way, we need a way to reproduce it.

**Comment by ntamas** [comment] 2021-04-14 15:02
@kloczek Can you please post the full command line that was used to compile one of the `-lexer.c` files (e.g., `dl-lexer.c`)? The compiler flags are supposed to contain `-Wno-unused-function` _already_, exactly because of problems like the one you see above, so I don't understand how this warning could still be triggered here. This is the part in `etc/cmake/compilers.cmake` that is responsible for setting up the compiler warnings:

```
target_compile_options(${TARGET_NAME} PRIVATE
      # GCC-style compilers:
      $<$<C_COMPILER_ID:GCC,Clang,AppleClang,Intel>:
        -Wall -Wextra -pedantic -Werror -Wno-unused-function -Wno-unused-parameter -Wno-sign-compare
      >
      $<$<BOOL:${COMPILER_SUPPORTS_NO_VARARGS_FLAG}>:-Wno-varargs>
      # Intel compiler:
      $<$<C_COMPILER_ID:Intel>:
        # disable #279: controlling expression is constant; affecting assert(condition && "message")
        # disable #188: enumerated type mixed with another type; affecting IGRAPH_CHECK
        # disable #592: variable "var" is used before its value is set; affecting IGRAPH_UNUSED
        -wd279 -wd188 -wd592 -diag-disable=remark
      >
    )
```

So, as long as CMake correctly identifies the compiler as `gcc`, `clang` or `icc`, `-Wno-unused-function` should be in the compiler flags.

**Comment by szhorvat** [comment] 2021-04-14 15:03
> ```
> src/centrality/prpack/prpack_solver.cpp:512: warning: ignoring '#pragma omp parallel' [-Wunknown-pragmas]
> ```
> 
> It looks like we might have to enable OpenMP pragmas separately for the compiler that you are using; which compiler is that?

I've only seen this when additional warning flags were used.

> ```
> src/isomorphism/bliss/partition.cc:967:22: warning: unused variable 'sorted' [-Wunused-variable]
> src/centrality/prpack/prpack_base_graph.cpp:170:12: warning: unused variable 'ignore' [-Wunused-variable]
> ```
> 
> These are harmless; these variables are used in assertions, which are optimized away by the compile due to `-NDEBUG`. @szhorvat, shall we replace this with `IGRAPH_ASSERT` so they are not optimized away?

This is not our own code, and both libraries are performance optimized. I'd rather not force keeping the `assert`s. I think it's fine to disable the warning specifically for these packages.

But once again: I don't think these would show up unless warnings are explicitly turned on. We already don't do that for bliss and prpack.

**Comment by ntamas** [comment] 2021-04-14 15:11
> I've only seen this when additional warning flags were used.

Nevertheless, I realized that indeed there are extra compiler flags that you might need to pass to `gcc` to enable OpenMP support (`-fopenmp`, for instance; macOS Clang requires `-Xclang -fopenmp` according to CMake). Hence, I've added some CMake magic to pass the correct flags in https://github.com/igraph/igraph/commit/b5fade2aef7937e9a40eba87394267cf00919227 .

**Comment by ntamas** [comment] 2021-04-14 15:11
> But once again: I don't think these would show up unless warnings are explicitly turned on. We already don't do that for bliss and prpack.

Indeed there is something weird with the warning configuration in the output posted by the OP. The warnings are clearly not set up in a way that we wanted them to be.

**Comment by szhorvat** [comment] 2021-04-17 15:56
> > Unfortunately we cannot do anything by this; we need to support macOS, which comes with an old version of Flex and Bison
> 
> I think the old Bison in macOS might support `%define api.pure` (I checked the other day), but some of the other warnings can't be fixed without breaking compatibility with macOS's default Bison.

No, macOS's Bison does not support `%define api.pure`, and it also does not support `-Wno-deprecated`.

**Comment by szhorvat** [comment] 2021-04-20 19:40
@kloczek Some of these have been improved. The remaining questions before this can be closed:

 - Does it cause any actual problems for you? It appears that some of these warnings have been forcibly enabled (they're not used by default by igraph).
 - Can you give steps to reproduce them? How do you compile, what compiler version and flags, etc. The ones that concern me a bit are those similar to `argument 1 value '18446744073709551615' exceeds maximum object size 9223372036854775807` However, it is unclear if this warning is even valid.

**Comment by kloczek** [comment] 2021-04-20 22:55
@szhorvat generally I've reported those warnings because it was a bit to many of them :P 
As I'm usimg quite fresh tooling which not all people still are using and I'm using LTO which quite often produces more warnings I've been thinking that it is worth to report what I found.
As some progress has been made and if you are happy with current state feel free to close that ticket.

I'm using usually gcc 11.0.1 from fedoira rawhide and today I'va managed to rebuild all my packages related to LLVM 12.0.0 stack soon will try as well build perform test build of all my packages using clang 12.0.0.
In case of usimg gcc I'm injecting into build procedure set of encv variables like below:
```console
[tkloczko@barrel SPECS]$ rpm -E %set_build_flags

CFLAGS="-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none";
CXXFLAGS="-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none";
FFLAGS="-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -I/usr/lib64/gfortran/modules";
FCFLAGS="-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -I/usr/lib64/gfortran/modules";
LDFLAGS="-Wl,-z,relro -Wl,--as-needed -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin";
CC="/usr/bin/gcc"; CXX="/usr/bin/g++"; FC="/usr/bin/gfortran";
AR="/usr/bin/gcc-ar"; NM="/usr/bin/gcc-nm"; RANLIB="/usr/bin/gcc-ranlib";
export CFLAGS CXXFLAGS FFLAGS FCFLAGS LDFLAGS CC CXX FC AR NM RANLIB;
```
That provides LTO optimisation and as well workaround to known gcc LTO bug which is use of `-flto=auto -flto-partition=none` which disables paralellisation of the LTO optimisation of the sibngle linked binary across multiple CPU cores however it causes ythat LTO optimised code is correct.
Set of `-spec=</some/file>`options injects into gcc or ld default options. So for example
```console
[tkloczko@barrel SPECS]$ cat /usr/lib/rpm/redhat/redhat-hardened-cc1
*cc1_options:
+ %{!r:%{!fpie:%{!fPIE:%{!fpic:%{!fPIC:%{!fno-pic:-fPIE}}}}}}
```
forces to generate by default PIE code (Position Independent Executable)
Other file
```console
[tkloczko@barrel SPECS]$ cat /usr/lib/rpm/redhat/redhat-annobin-cc1
*cc1_options:
+ %{!-fno-use-annobin:%{!iplugindir*:%:find-plugindir()} -fplugin=annobin}
```
forces to use annonbin gcc plugin which saves in separated ELF section compiler settings.
As `igraph` uses cmake here is definition of my %cmake macro which I'm using on building my all rpm packages:
```console
[tkloczko@barrel SPECS]$ rpm -E %cmake

CFLAGS="-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none";
CXXFLAGS="-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none";
FFLAGS="-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -I/usr/lib64/gfortran/modules";
FCFLAGS="-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -I/usr/lib64/gfortran/modules";
LDFLAGS="-Wl,-z,relro -Wl,--as-needed -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin";
CC="/usr/bin/gcc"; CXX="/usr/bin/g++"; FC="/usr/bin/gfortran";
AR="/usr/bin/gcc-ar"; NM="/usr/bin/gcc-nm"; RANLIB="/usr/bin/gcc-ranlib";
export CFLAGS CXXFLAGS FFLAGS FCFLAGS LDFLAGS CC CXX FC AR NM RANLIB;

        /usr/bin/cmake \
        -B x86_64-redhat-linux-gnu \
        -D BUILD_SHARED_LIBS=ON \
        -D CMAKE_AR="$AR" \
        -D CMAKE_BUILD_TYPE=RelWithDebInfo \
        -D CMAKE_C_FLAGS_RELEASE="-DNDEBUG" \
        -D CMAKE_CXX_FLAGS_RELEASE="-DNDEBUG" \
        -D CMAKE_Fortran_FLAGS_RELEASE="-DNDEBUG" \
        -D CMAKE_INSTALL_PREFIX=/usr \
        -D CMAKE_NM="$NM" \
        -D CMAKE_RANLIB="$RANLIB" \
        -D CMAKE_VERBOSE_MAKEFILE=ON \
        -D DBUILD_SHARED_LIBS=ON \
        -D INCLUDE_INSTALL_DIR=/usr/include \
        -D LIB_INSTALL_DIR=/usr/lib64 \
%if "lib64" == "lib64"
        -D LIB_SUFFIX=64 \
%endif
        -D SHARE_INSTALL_PREFIX=/usr/share \
        -D SYSCONF_INSTALL_DIR=/etc \
        -S .
```
Just FTR I'm using exactly thje same set of rpm macros as fedora and my build env at the moment consist from about 80% of packages build by me using my own methodology.
If you may have more questions about my build env I'll be glad to sescribe all necessary details :)
And thank you very much to your time spend on looking closer on all those warnings :)

**Comment by szhorvat** [comment] 2021-05-31 13:12
Thanks for the detailed comments!

I took another look at this today, using GCC 11.1.0 as included in MacPorts. Since I am on macOS, I needed to remove some of the options (especially linker options). For my own reference:

```
CFLAGS="-O2 -g -grecord-gcc-switches -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none";
CXXFLAGS="-O2 -g -grecord-gcc-switches -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none";
LDFLAGS="-flto=auto -flto-partition=none";
CC="/opt/local/bin/gcc-mp-11"; CXX="/opt/local/bin/g++-mp-11";
AR="/opt/local/bin/gcc-ar-mp-11"; NM="/opt/local/bin/gcc-nm-mp-11"; RANLIB="/opt/local/bin/gcc-ranlib-mp-11";
export CFLAGS CXXFLAGS LDFLAGS CC CXX AR NM RANLIB;


cmake \
        -G "Unix Makefiles" \
        -D BUILD_SHARED_LIBS=ON \
        -D CMAKE_AR="$AR" \
        -D CMAKE_BUILD_TYPE=RelWithDebInfo \
        -D CMAKE_C_FLAGS_RELEASE="-DNDEBUG" \
        -D CMAKE_CXX_FLAGS_RELEASE="-DNDEBUG" \
        -D CMAKE_NM="$NM" \
        -D CMAKE_RANLIB="$RANLIB" \
        -D CMAKE_VERBOSE_MAKEFILE=ON \
        -S ..
```

I can reproduce some of the `-Wmaybe-uninitialized` warnings.

Those which concern the first argument of `igraph_vector_view()` are incorrect and can be ignored.

I believe the one concerning `no_of_neighbors` in `recent_degree.c` is a false positive.

I was unable to reproduce any other warnings, however, I was also unable to complete compilation. The linker crashes with "Too many open files" even after raising the system setting to allow 100,000 files. This may be due to some difference between macOS and Linux.

I will close this now, and we can continue if something serious-looking crops up in the next version of igraph, or if we manage to reproduce more of the warnings.

**Closed by szhorvat** 2021-05-31 13:12 UTC
