### ISSUE TITLE
SIGSEGV segfault in Graph.get_shortest_paths()

### ISSUE THREAD

**Issue by glassworks-projects** [igraph/igraph#2321] opened 2023-03-10 17:03 UTC
Hi, I am experiencing a memory issue when using `get_shortest_paths()`. It doesn't always happen, and it seems to have to do with the structure of the graph on which it's being called. I have tried to reduce my code to a minimum reproducible example:

```python
import pandas as pd
import numpy as np
from igraph import Graph


def convert_to_weighted_edgelist(df: pd.DataFrame):
    # edges must be presorted in ascending order (s.t. artist_a < artist_b)
    mx = np.sort(df[['artist_a', 'artist_b']].to_numpy(), axis=1)
    unique, counts = np.unique(mx, return_counts=True, axis=0)
    return np.c_[unique, counts]


def ego_subgraph(g: Graph, vertex_id: int, order: int = 1):
    return g.induced_subgraph(g.neighborhood(vertex_id, order))


def path_lengths(g: Graph, focal_vertex_id: int, order=1):
    # for each vertex in subgraph, find path length from that vertex to focal_vertex
    # return: {vertex : length}
    subgraph = ego_subgraph(g, focal_vertex_id, order)

    # the offending call
    print("next call will cause segfault:")
    shortest_paths = subgraph.get_shortest_paths(focal_vertex_id, weights='weight')


def scale(weight: int):
    return 1 / weight


def main():
    data = pd.read_csv('edges.csv')
    edgelist = convert_to_weighted_edgelist(data)

    g = Graph.TupleList(
        list(map(lambda x: (x[0].astype(str), x[1].astype(str), scale(x[2])), edgelist)),
        weights=True
    )

    artist = "417"
    path_lengths(g, g.vs['name'].index(artist), order=1)


if __name__ == "__main__":
    main()
```

When run, the output is:
```
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

But if the order is increased (i.e., `path_lengths(g, g.vs['name'].index(artist), order=2)`), the fault does not occur, at least not for this specific artist ID. It does occur for other artist IDs though. 

Data to run this code can be found at https://github.com/glassworks-projects/colisten/blob/main/data/edges.csv

- [x] This issue is for the Python interface of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

**Comment by szhorvat** [comment] 2023-03-10 21:32
Actually this was a problem in the C core, as well as a problem in the way you used igraph, @glassworks-projects . Thanks for reporting the issue with a clean reproducer!

The igraph bug was that the source vertex ID was not validated. This is now fixed in e7a25a2113e5c0a472b88aae2dd8161797be7446

The problem in your code is that you are passing an invalid vertex ID in `focal_vertex_id` here:

```python
shortest_paths = subgraph.get_shortest_paths(focal_vertex_id, weights='weight')
```

When you take a subgraph, the vertex IDs will change because in igraph, vertices are always numbered from `0` to `vcount - 1`. It would probably be best for your use case to refer to vertices by name instead of ID (i.e. assign a string name to each). Perhaps @ntamas can comment on this further.

**Closed by szhorvat** 2023-03-10 21:32 UTC

**Comment by szhorvat** [comment] 2023-03-10 22:29
This is now backported to 0.9 for the sake of the R interface, 98304787bc811bf709be5aeddea7b570c370988e

**Comment by glassworks-projects** [comment] 2023-03-10 23:22
thank you @szhorvat ! that makes sense. I'll work on a fix in my code. For reference, I'm on `igraph==0.10.4` and Mac OS 12.6.

**Comment by ntamas** [comment] 2023-03-15 14:55
>  Perhaps @ntamas can comment on this further.

All that's there to say is that the `"name"` vertex attribute is indexed behind the scenes into a dict that allows you to look up a vertex by its name in O(1) amortized time if the graph does not change. When the graph changes, the lookup table is invalidated and it is reconstructed again the next time it is needed.

So, if you do lots of vertex lookups by name and you are mutating the graph only occasionally, you can gain some performance and also improve readability by referring to vertices with a _string_ (which is interpreted as a vertex name).
