### ISSUE TITLE
layout_with_fr error: At core/layout/fruchterman_reingold.c:401 : Weights must be positive for Fruchterman-Reingold layout. Invalid value

### ISSUE THREAD

**Issue by parkjooyoung99** [igraph/igraph#2183] opened 2022-09-03 09:03 UTC
**Describe the bug**

As title, i am having trouble with error
At core/layout/fruchterman_reingold.c:401 : Weights must be positive for Fruchterman-Reingold layout. Invalid value
while running 'layout_with_fr'

I checked my igraph object by 

`which(igraph::E(g)$weight < 0)
`
and checked non of them were negative.

I want to know what weight that 'Fruchterman-Reingold layout' use from igraph object (the input).
Thank you!

**To reproduce**
I am so sorry that i cannot upload my object.
If my professor allows me to, I will update it.

**Version information**
igraph 1.3.4

obtained it while installing 'veloviz R' with 
`BiocManager::install("veloviz")`

**Comment by GroteGnoom** [comment] 2022-09-03 09:26
Is any of your weights zero? With 'positive' we mean greater than zero.

**Comment by parkjooyoung99** [comment] 2022-09-03 14:30
if there are some, would there be any way to solve this?

**Comment by szhorvat** [comment] 2022-09-03 15:03
The Fruchterman-Reingold layout does not work with zero or negative weights. Transform the weights before plotting, or remove them entirely. See the `weights` parameter of `layout_with_fr`.

Check the documentation [here](https://igraph.org/c/html/latest/igraph-Layout.html#igraph_layout_fruchterman_reingold) to see how the weights are interpreted.

I am closing this issue now since this is a support request, not a bug report, and therefore should have been posted [on the forum](https://igraph.discourse.group/).

**Closed by szhorvat** 2022-09-03 15:03 UTC
