### ISSUE TITLE
Problems reading a file in DL format

### ISSUE THREAD

**Issue by JJ** [igraph/igraph#2246] opened 2022-10-25 12:54 UTC
**Describe the bug**

I get an error when reading this file using

```R
read_graph( "alemania.test.txt",format="dl")
```

The error says:

```
Error in read.graph.dl(file, ...) : 
  At core/io/dl.c:93 : syntax error, unexpected end of file, expecting DL in line 1, Parse error
```

[alemania.test.txt](https://github.com/igraph/igraph/files/9860396/alemania.test.txt)

**To reproduce**

Code above and attached file should be enough

**Version information**

Latest version, from CRAN.

**Comment by ntamas** [comment] 2022-10-25 13:14
igraph's DL reader is kinda limited at its present form; I have found the following issues while trying to get your file parsed:

* It looks like the `DL` header and the `N=...` part has to be on the same line, otherwise igraph's parser won't accept it
* `DIAGONAL PRESENT` is not supported; the code works if I remove it so the `FORMAT` line looks like `FORMAT = FULLMATRIX` only
* Weights in the adjacency matrix are not supported

So, all in all I'd advise using a different format if possible. We might improve the DL parser in the future, but at the moment it's low priority given the lack of formal documentation for this file format.

**Comment by szhorvat** [comment] 2022-10-25 16:08
I looked at improving the DL reader last summer, but it's almost hopeless. My impression is that this is not a true exchange format. It's just a file containing commands for UCINET, i.e. a full support would require implementing an interpreter for its command language. It does not help that UCINET is closed-source Windows-only software that one needs to buy a license for. The language/format is not formally documented, e.g. there is no documentation that I could find that makes it clear that DL and N can be on different lines. 

My conclusion is that it will not be productive to put effort into trying to improve igraph's DL format. It would have to be done based on guesswork and looking at examples anyway.

> So, all in all I'd advise using a different format if possible.

I agree about this.

**Comment by JJ** [comment] 2022-10-25 17:44
Adding insult to injury, there are many variants. I finally opted for writing a (very ad hoc) parser in Rakulang and transform it to an adjacency matrix.
Thanks anyway! If you will, I will opt not to close the issue just in case some other people want to suggest workarounds or, who knows, create a whole parser...

**Comment by szhorvat** [comment] 2022-10-26 09:01
What's missing for this issue is a clear and precise documentation of the format. If someone (preferably a person with access to UCINET) can write that up, I can have another go at improving the parser.

**Comment by szhorvat** [comment] 2022-12-10 09:19
Duplicate of #2052.

**Closed by szhorvat** 2022-12-10 09:19 UTC
Labels: wishlist
