### ISSUE TITLE
test failure in No.25 and No.32 when test functions

### ISSUE THREAD

**Issue by Yanglinjun1** [igraph/igraph#1064] opened 2018-02-23 05:26 UTC
Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] This issue is for the C core of igraph.
- [x] This issue is a bug report or a feature request, not a support question.
[testsuite.log](https://github.com/igraph/igraph/files/1750550/testsuite.log)

**Comment by ntamas** [comment] 2018-02-23 14:54
Thanks for the report. I think these are harmless - the configure script is actually complaining because there were compiler warnings emitted during the compilation of the test cases because we have accidentally used `abs` instead of `fabs` to take the absolute values of some floating-point numbers. Replacing `abs` with `fabs` in `examples/simple/igraph_sparsemat4.c` and `examples/simple/spmatrix.c` will probably solve the issue.

**Comment by ntamas** [comment] 2018-02-23 14:55
Actually, `spmatrix.c` should use `labs`, not `fabs`.

**Comment by ntamas** [comment] 2018-02-23 14:56
Duplicate of #857, already fixed in https://github.com/igraph/igraph/commit/ca8355ae35e05570ee56ac354a4146c0c8f7a8ec

**Closed by ntamas** 2018-02-23 14:56 UTC
